min_version = "2026.10.0"

[plugins]
chunkzero = "https://github.com/chunkzero/mise-chunkzero"

[settings]
idiomatic_version_file_enable_tools = ["rust"]

[tools]
java = "temurin-25.0.4+7.0.LTS"
just = "1.58.0"
ktlint = "1.8.0"
node = "24.21.0"
pnpm = "10.33.0"
"github:google/google-java-format" = { version = "1.36.1", bin = "google-java-format" }
"chunkzero:rpp-nightly" = "0.1.0-nightly.20261008133812.g121b31a3e9a2"
