import type { IndustrialPresetOptions, Theme } from "./types.ts";

function industrial(opts: IndustrialPresetOptions = {}): Theme {
    const shell = opts.shell_fill ?? "#172f69";
    const panel = opts.panel_fill ?? "#087cac";
    const surface = opts.surface_fill ?? "#086d99";
    const deep = opts.deep_fill ?? "#071a43";
    const border = opts.border_color ?? "#03091f";
    const cyan = opts.highlight_color ?? "#25c9ec";
    const cyanDark = opts.cyan_dark ?? "#07517f";
    const accent = opts.accent_color ?? "#ff8300";
    const accentLight = opts.accent_light ?? "#ffb20b";
    const accentDark = opts.accent_dark ?? "#a92e00";
    const danger = opts.danger_color ?? "#ed171b";
    const dangerDark = opts.danger_dark ?? "#75000d";
    const confirm = opts.confirm_color ?? "#20c900";
    const confirmDark = opts.confirm_dark ?? "#087500";

    return {
        frames: {
            shell: {
                kind: "panel",
                fill: shell,
                border_color: border,
                border_width: 2,
                radius: 0,
                inset_depth: 2,
                highlight_color: "#34589a",
                shadow_color: "#040a24",
            },
            panel: {
                kind: "panel",
                fill: panel,
                border_color: border,
                border_width: 2,
                radius: 0,
                inset_depth: 2,
                highlight_color: cyan,
                shadow_color: deep,
            },
            surface: {
                kind: "panel",
                fill: surface,
                border_color: border,
                border_width: 2,
                radius: 0,
                inset_depth: 2,
                highlight_color: cyan,
                shadow_color: deep,
            },
            header: {
                kind: "panel",
                fill: opts.header_fill ?? "#087baa",
                border_color: border,
                border_width: 2,
                radius: 0,
                inset_depth: 2,
                highlight_color: cyan,
                shadow_color: deep,
            },
            rail: {
                kind: "panel",
                fill: shell,
                border_color: border,
                border_width: 1,
                radius: 0,
                inset_depth: 1,
                highlight_color: "#34589a",
                shadow_color: deep,
            },
            recess: {
                kind: "panel",
                fill: deep,
                border_color: border,
                border_width: 2,
                radius: 0,
                inset_depth: 1,
                highlight_color: cyanDark,
                shadow_color: border,
            },
            button: {
                kind: "button",
                fill: opts.button_fill ?? "#0994c6",
                border_color: border,
                border_width: 2,
                radius: 0,
                inset_depth: 2,
                highlight_color: cyan,
                shadow_color: cyanDark,
            },
            button_accent: {
                kind: "button",
                fill: accent,
                border_color: accentDark,
                border_width: 2,
                radius: 0,
                inset_depth: 2,
                highlight_color: accentLight,
                shadow_color: accentDark,
            },
            button_danger: {
                kind: "button",
                fill: danger,
                border_color: dangerDark,
                border_width: 2,
                radius: 0,
                inset_depth: 2,
                highlight_color: "#ff5b45",
                shadow_color: dangerDark,
            },
            button_confirm: {
                kind: "button",
                fill: confirm,
                border_color: confirmDark,
                border_width: 2,
                radius: 0,
                inset_depth: 2,
                highlight_color: "#78f02d",
                shadow_color: confirmDark,
            },
            tab: {
                kind: "button",
                fill: opts.tab_fill ?? "#078cbc",
                border_color: border,
                border_width: 2,
                radius: 0,
                inset_depth: 2,
                highlight_color: cyan,
                shadow_color: cyanDark,
            },
            tab_active: {
                kind: "button",
                fill: accent,
                border_color: accentDark,
                border_width: 2,
                radius: 0,
                inset_depth: 2,
                highlight_color: accentLight,
                shadow_color: accentDark,
            },
            hud_panel: {
                kind: "panel",
                fill: shell,
                border_color: border,
                border_width: 2,
                radius: 0,
                inset_depth: 2,
                highlight_color: "#34589a",
                shadow_color: deep,
            },
            hud_chip: {
                kind: "button",
                fill: deep,
                border_color: cyanDark,
                border_width: 1,
                radius: 0,
                inset_depth: 1,
                highlight_color: cyan,
                shadow_color: border,
            },
            hud_focus: {
                kind: "panel",
                fill: surface,
                border_color: accentDark,
                border_width: 2,
                radius: 0,
                inset_depth: 2,
                highlight_color: accentLight,
                shadow_color: deep,
            },
            title_bar: {
                kind: "panel",
                fill: opts.title_fill ?? "#087baa",
                border_color: border,
                border_width: 2,
                radius: 0,
                inset_depth: 2,
                highlight_color: cyan,
                shadow_color: deep,
            },
            slot_cell: {
                kind: "slot",
                fill: opts.slot_fill ?? "#07577d",
                border_color: cyanDark,
                border_width: 2,
                radius: 0,
                inset_depth: 1,
                highlight_color: cyan,
                shadow_color: border,
            },
            search_field: {
                kind: "panel",
                fill: opts.search_fill ?? "#243f7b",
                border_color: border,
                border_width: 2,
                radius: 0,
                inset_depth: 2,
                highlight_color: cyan,
                shadow_color: deep,
            },
            vent: {
                kind: "vent",
                fill: opts.vent_fill ?? "#12396b",
                border_color: border,
                border_width: 1,
                radius: 0,
                inset_depth: 1,
                highlight_color: cyanDark,
                accent_color: opts.vent_color ?? "#061536",
                shadow_color: border,
            },
            hazard_bar: {
                kind: "hazard_bar",
                fill: accentLight,
                border_color: accentDark,
                border_width: 2,
                radius: 0,
                inset_depth: 0,
                highlight_color: "#ffd53b",
                shadow_color: accentDark,
                stripe_color: opts.stripe_color ?? "#c43100",
                stripe_shadow_color: opts.stripe_shadow_color ?? "#5c1200",
                stripe_width: opts.stripe_width ?? 8,
            },
        },
        sprites: {
            pack_badge: {
                kind: "badge",
                width: 28,
                height: 14,
                fill: accent,
                border_color: accentDark,
                border_width: 2,
                radius: 0,
                inset_depth: 2,
                highlight_color: accentLight,
                shadow_color: accentDark,
                accent_color: opts.badge_accent ?? deep,
            },
        },
    };
}

export const presets: { industrial: typeof industrial } = { industrial };
