package dev.oglass.window.codegen

import dev.oglass.window.codegen.manifest.parseManifest
import io.kotest.assertions.throwables.shouldThrow
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain

class GeneratorTest :
    StringSpec({
        fun generateSingle(
            json: String,
            pkg: String = "com.example.ui",
        ): String {
            val files = Generator.generate(parseManifest(json), pkg)
            files.size shouldBe 1
            return files.first().content
        }

        "golden: shop window with dynamic slot and two buttons" {
            val json =
                """
                {
                  "version": 5,
                  "windows": {
                    "shop": {
                      "slots": {
                        "title": { "x": 8, "y": 6 },
                        "buy_label": { "x": 58, "y": 196, "text": "Buy" }
                      },
                      "buttons": {
                        "buy": { "default": null },
                        "exit": { "default": "close" }
                      }
                    }
                  }
                }
                """.trimIndent()

            val expected =
                """
                // Generated by window-codegen — do not edit.
                package com.example.ui

                import dev.oglass.window.Click
                import dev.oglass.window.WindowScope
                import dev.oglass.window.WindowView
                import net.kyori.adventure.text.Component

                /** Typed view for the `shop` window. Implement the abstract members. */
                public abstract class ShopView : WindowView("shop") {
                    /** Render the `title` slot. */
                    protected abstract fun title(): Component

                    /** Handle a click on the `buy` button. */
                    protected abstract fun onBuy(click: Click)

                    /** Handle a click on the `exit` button (default: close the window). */
                    protected open fun onExit(click: Click): Unit = close()

                    final override fun WindowScope.bind() {
                        slot("title") { title() }
                        button("buy", ::onBuy)
                        button("exit", ::onExit)
                    }
                }
                """.trimIndent() + "\n"

            generateSingle(json) shouldBe expected
        }

        "golden: window with no dynamic slots and no buttons is an open class" {
            val json =
                """
                {
                  "version": 5,
                  "windows": {
                    "info_panel": {
                      "slots": { "header": { "text": "Welcome" } },
                      "buttons": {}
                    }
                  }
                }
                """.trimIndent()

            val expected =
                """
                // Generated by window-codegen — do not edit.
                package com.example.ui

                import dev.oglass.window.WindowScope
                import dev.oglass.window.WindowView

                /** Typed view for the `info_panel` window. Implement the abstract members. */
                public open class InfoPanelView : WindowView("info_panel") {
                    final override fun WindowScope.bind() {}
                }
                """.trimIndent() + "\n"

            generateSingle(json) shouldBe expected
        }

        "repeater groups generate indexed methods" {
            val json =
                """
                {
                  "version": 5,
                  "windows": {
                    "shop": {
                      "slots": {
                        "entry_price_0": {},
                        "entry_price_1": {}
                      },
                      "sprite_slots": {
                        "entry_icon_0": {},
                        "entry_icon_1": {}
                      },
                      "buttons": {
                        "entry_0": { "default": null },
                        "entry_1": { "default": null }
                      },
                      "groups": {
                        "entry": {
                          "count": 2,
                          "slots": { "price": ["entry_price_0", "entry_price_1"] },
                          "sprite_slots": { "icon": ["entry_icon_0", "entry_icon_1"] },
                          "buttons": ["entry_0", "entry_1"]
                        }
                      }
                    }
                  }
                }
                """.trimIndent()

            val content = generateSingle(json)
            content shouldContain "protected abstract fun entryPrice(index: Int): Component"
            content shouldContain "protected abstract fun entryIconSprite(index: Int): String?"
            content shouldContain "protected abstract fun onEntry(click: IndexedClick)"
            content shouldContain "slot(\"entry_price_0\") { entryPrice(0) }"
            content shouldContain "sprite(\"entry_icon_1\") { entryIconSprite(1) }"
            content shouldContain "button(\"entry_0\") { click ->"
            content shouldContain
                "IndexedClick(click.player, click.slot, 0, click.shift, click.right)"
            content.contains("entryPrice0") shouldBe false
        }

        "golden: slots-only window omits the Click import" {
            val json =
                """
                {
                  "version": 5,
                  "windows": { "stats": { "slots": { "kills": {} }, "buttons": {} } }
                }
                """.trimIndent()

            val expected =
                """
                // Generated by window-codegen — do not edit.
                package com.example.ui

                import dev.oglass.window.WindowScope
                import dev.oglass.window.WindowView
                import net.kyori.adventure.text.Component

                /** Typed view for the `stats` window. Implement the abstract members. */
                public abstract class StatsView : WindowView("stats") {
                    /** Render the `kills` slot. */
                    protected abstract fun kills(): Component

                    final override fun WindowScope.bind() {
                        slot("kills") { kills() }
                    }
                }
                """.trimIndent() + "\n"

            generateSingle(json) shouldBe expected
        }

        "golden: buttons-only window omits the Component import" {
            val json =
                """
                {
                  "version": 5,
                  "windows": { "menu": { "slots": {}, "buttons": { "play": { "default": null } } } }
                }
                """.trimIndent()

            val expected =
                """
                // Generated by window-codegen — do not edit.
                package com.example.ui

                import dev.oglass.window.Click
                import dev.oglass.window.WindowScope
                import dev.oglass.window.WindowView

                /** Typed view for the `menu` window. Implement the abstract members. */
                public abstract class MenuView : WindowView("menu") {
                    /** Handle a click on the `play` button. */
                    protected abstract fun onPlay(click: Click)

                    final override fun WindowScope.bind() {
                        button("play", ::onPlay)
                    }
                }
                """.trimIndent() + "\n"

            generateSingle(json) shouldBe expected
        }

        "golden: HUD with dynamic slot" {
            val json =
                """
                {
                  "version": 5,
                  "huds": {
                    "status": {
                      "slots": {
                        "coins": {},
                        "label_0": { "text": "Coins" }
                      }
                    }
                  }
                }
                """.trimIndent()

            val expected =
                """
                // Generated by window-codegen — do not edit.
                package com.example.ui

                import dev.oglass.window.HudScope
                import dev.oglass.window.HudView
                import net.kyori.adventure.text.Component

                /** Typed view for the `status` HUD. Implement the abstract members. */
                public abstract class StatusHud : HudView("status") {
                    /** Render the `coins` slot. */
                    protected abstract fun coins(): Component

                    final override fun HudScope.bind() {
                        slot("coins") { coins() }
                    }
                }
                """.trimIndent() + "\n"

            generateSingle(json) shouldBe expected
        }

        "name mangling: window/slot/button" {
            Naming.className("shop_menu") shouldBe "ShopMenuView"
            Naming.className("shop") shouldBe "ShopView"
            Naming.hudClassName("status_bar") shouldBe "StatusBarHud"
            Naming.slotMember("buy_now") shouldBe "buyNow"
            Naming.slotMember("title") shouldBe "title"
            Naming.buttonMember("buy_now") shouldBe "onBuyNow"
            Naming.buttonMember("exit") shouldBe "onExit"
        }

        "static labels are skipped" {
            val json =
                """
                {
                  "version": 5,
                  "windows": {
                    "shop": {
                      "slots": {
                        "price": { "text": "Static" },
                        "amount": {}
                      },
                      "buttons": {}
                    }
                  }
                }
                """.trimIndent()
            val content = generateSingle(json)
            content shouldContain "fun amount(): Component"
            content.contains("fun price()") shouldBe false
        }

        "default close renders open member" {
            val json =
                """
                {
                  "version": 5,
                  "windows": {
                    "shop": { "slots": {}, "buttons": { "leave": { "default": "close" } } }
                  }
                }
                """.trimIndent()
            generateSingle(json) shouldContain
                "protected open fun onLeave(click: Click): Unit = close()"
        }

        "collision between two members is an error" {
            // slot `buy_now` -> buyNow; button `buy_now`... no, buttons get on-prefix.
            // Use two slots that collide: `buy_now` and `buyNow`-equivalent is impossible from
            // manifest names (they are lowercase). Instead two slots normalizing identically:
            // `buy_now` and `buynow` both differ; use a slot and a snake variant that collide via
            // camel: `a_b` -> aB and... craft a real collision: slot `on_buy` -> onBuy, button
            // `buy`
            // -> onBuy.
            val json =
                """
                {
                  "version": 5,
                  "windows": {
                    "shop": {
                      "slots": { "on_buy": {} },
                      "buttons": { "buy": { "default": null } }
                    }
                  }
                }
                """.trimIndent()
            val ex = shouldThrow<GenerationException> { generateSingle(json) }
            ex.message shouldContain "onBuy"
        }

        "reserved member collision (slot named player)" {
            val json =
                """
                {
                  "version": 5,
                  "windows": { "shop": { "slots": { "player": {} }, "buttons": {} } }
                }
                """.trimIndent()
            val ex = shouldThrow<GenerationException> { generateSingle(json) }
            ex.message shouldContain "reserved"
        }

        "rejects unsupported manifest version" {
            val ex =
                shouldThrow<IllegalArgumentException> {
                    parseManifest("""{ "version": 1, "windows": {} }""")
                }
            ex.message shouldContain "version"
        }

        "windows are emitted in sorted order" {
            val json =
                """
                {
                  "version": 5,
                  "windows": {
                    "zebra": { "slots": {}, "buttons": {} },
                    "alpha": { "slots": {}, "buttons": {} }
                  }
                }
                """.trimIndent()
            val files = Generator.generate(parseManifest(json), "x")
            files.map { it.fileName } shouldBe listOf("AlphaView.kt", "ZebraView.kt")
        }
    })
