package com.chunkzero.window.example

import net.minestom.server.item.Material

val MARKET_CATALOG: List<Product> =
    listOf(
        Product(
            "diamond",
            "Diamond Cache",
            Material.DIAMOND,
            480,
            ProductTier.EPIC,
            ProductCategory.GEAR,
            true,
        ),
        Product(
            "emerald",
            "Emerald Voucher",
            Material.EMERALD,
            320,
            ProductTier.RARE,
            ProductCategory.GEAR,
            true,
        ),
        Product(
            "gold",
            "Gilded Ingot",
            Material.GOLD_INGOT,
            180,
            ProductTier.RARE,
            ProductCategory.GEAR,
        ),
        Product(
            "iron",
            "Tempered Iron",
            Material.IRON_INGOT,
            95,
            ProductTier.COMMON,
            ProductCategory.GEAR,
        ),
        Product(
            "copper",
            "Copper Bundle",
            Material.COPPER_INGOT,
            75,
            ProductTier.COMMON,
            ProductCategory.GEAR,
        ),
        Product(
            "redstone",
            "Redstone Kit",
            Material.REDSTONE,
            110,
            ProductTier.COMMON,
            ProductCategory.GEAR,
        ),
        Product(
            "lapis",
            "Lapis Bundle",
            Material.LAPIS_LAZULI,
            125,
            ProductTier.COMMON,
            ProductCategory.MAGIC,
        ),
        Product(
            "coal",
            "Compressed Coal",
            Material.COAL,
            60,
            ProductTier.COMMON,
            ProductCategory.GEAR,
        ),
        Product(
            "quartz",
            "Quartz Prism",
            Material.QUARTZ,
            140,
            ProductTier.RARE,
            ProductCategory.MAGIC,
        ),
        Product(
            "amethyst",
            "Amethyst Song",
            Material.AMETHYST_SHARD,
            210,
            ProductTier.RARE,
            ProductCategory.MAGIC,
            true,
        ),
        Product(
            "ender_pearl",
            "Ender Pearl",
            Material.ENDER_PEARL,
            240,
            ProductTier.RARE,
            ProductCategory.MAGIC,
        ),
        Product(
            "blaze_rod",
            "Blaze Conduit",
            Material.BLAZE_ROD,
            275,
            ProductTier.RARE,
            ProductCategory.MAGIC,
        ),
        Product(
            "ghast_tear",
            "Ghast Tear",
            Material.GHAST_TEAR,
            390,
            ProductTier.EPIC,
            ProductCategory.MAGIC,
        ),
        Product(
            "prismarine",
            "Prismarine Core",
            Material.PRISMARINE_SHARD,
            225,
            ProductTier.RARE,
            ProductCategory.MAGIC,
        ),
        Product(
            "heart",
            "Heart of the Sea",
            Material.HEART_OF_THE_SEA,
            760,
            ProductTier.LEGENDARY,
            ProductCategory.MAGIC,
            true,
        ),
        Product(
            "nether_star",
            "Nether Star",
            Material.NETHER_STAR,
            1_200,
            ProductTier.LEGENDARY,
            ProductCategory.MAGIC,
            true,
        ),
        Product(
            "totem",
            "Totem Charm",
            Material.TOTEM_OF_UNDYING,
            940,
            ProductTier.LEGENDARY,
            ProductCategory.MAGIC,
        ),
        Product(
            "trident",
            "Tide Trident",
            Material.TRIDENT,
            860,
            ProductTier.LEGENDARY,
            ProductCategory.GEAR,
            true,
        ),
        Product(
            "elytra",
            "Sky Wings",
            Material.ELYTRA,
            1_150,
            ProductTier.LEGENDARY,
            ProductCategory.GEAR,
            true,
        ),
        Product(
            "rocket",
            "Rocket Crate",
            Material.FIREWORK_ROCKET,
            155,
            ProductTier.COMMON,
            ProductCategory.GEAR,
        ),
        Product(
            "golden_apple",
            "Golden Apple",
            Material.GOLDEN_APPLE,
            420,
            ProductTier.EPIC,
            ProductCategory.MAGIC,
        ),
        Product(
            "experience",
            "Experience Flask",
            Material.EXPERIENCE_BOTTLE,
            195,
            ProductTier.RARE,
            ProductCategory.MAGIC,
        ),
        Product(
            "book",
            "Arcane Manual",
            Material.ENCHANTED_BOOK,
            340,
            ProductTier.EPIC,
            ProductCategory.MAGIC,
        ),
        Product(
            "spyglass",
            "Scout Spyglass",
            Material.SPYGLASS,
            165,
            ProductTier.COMMON,
            ProductCategory.GEAR,
        ),
        Product(
            "compass",
            "Explorer Compass",
            Material.COMPASS,
            205,
            ProductTier.RARE,
            ProductCategory.GEAR,
        ),
        Product(
            "clock",
            "Chrono Dial",
            Material.CLOCK,
            260,
            ProductTier.RARE,
            ProductCategory.GEAR,
        ),
        Product(
            "name_tag",
            "Identity Tag",
            Material.NAME_TAG,
            135,
            ProductTier.COMMON,
            ProductCategory.GEAR,
        ),
        Product(
            "saddle",
            "Ranger Saddle",
            Material.SADDLE,
            285,
            ProductTier.RARE,
            ProductCategory.GEAR,
        ),
        Product(
            "shell",
            "Shulker Shell",
            Material.SHULKER_SHELL,
            510,
            ProductTier.EPIC,
            ProductCategory.GEAR,
        ),
        Product(
            "echo",
            "Echo Shard",
            Material.ECHO_SHARD,
            620,
            ProductTier.EPIC,
            ProductCategory.MAGIC,
        ),
    )
