[versions]
kotlin = "2.3.10"
minestom = "2026.09.12-26.2"
multistom = "0.1.0-nightly.20261005021334.g24a253a8ad29"
adventure = "5.1.1"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.10.0"
kotest = "6.1.3"
slf4j = "2.0.18"

shadow = "9.3.1"
dokka = "2.1.0"

[libraries]
minestom = { group = "net.minestom", name = "minestom", version.ref = "minestom" }
multistom = { group = "com.chunkzero.multistom", name = "multistom", version.ref = "multistom" }
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-text-serializer-plain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
kotest-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-junit = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }

plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
plugin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
plugin-dokka = { module = "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin", version.ref = "dokka" }

[bundles]
test = ["kotest-core", "kotest-junit"]
