//! Kotlin source generation from compiled Window UI data.

use crate::Result;
use crate::manifest::{FontMetricsEntry, Manifest};
use crate::pipeline::OutputFile;

mod hud;
mod menu;
mod naming;
mod views;

use views::{font_metrics_expr, kt_string, render_char_int_map, render_int_int_map};

const HEADER: &str = "// Generated by window-codegen — do not edit.";
const INDENT: &str = "    ";
const INDENT2: &str = "        ";

/// Generate typed Kotlin view subclasses, one file per manifest window/HUD.
pub fn generate_kotlin(manifest: &Manifest, package_name: &str) -> Result<Vec<OutputFile>> {
    naming::validate_package(package_name)?;
    let mut files = Vec::with_capacity(6 + manifest.windows.len() + manifest.huds.len());
    files.push(generate_pack(manifest, package_name));
    files.push(generate_spacers(manifest, package_name));
    files.push(generate_fonts(manifest, package_name));
    files.push(generate_sprites(manifest, package_name));
    files.push(menu::generate_window_definitions(manifest, package_name));
    files.push(hud::generate_hud_definitions(manifest, package_name));
    for (name, window) in &manifest.windows {
        files.push(menu::generate_window(name, window, package_name)?);
    }
    for (name, hud) in &manifest.huds {
        files.push(hud::generate_hud(name, hud, package_name)?);
    }
    files.sort_by(|a, b| a.path.cmp(&b.path));
    Ok(files)
}

fn render_pack(manifest: &Manifest, package_name: &str) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');
    out.push_str("package ");
    out.push_str(package_name);
    out.push_str("\n\n");
    out.push_str("import dev.oglass.window.Windows\n");
    out.push_str("import dev.oglass.window.manifest.WindowManifest\n\n");
    out.push_str("/** Compiled Window pack definition. */\n");
    out.push_str("public object WindowPack {\n");
    out.push_str(INDENT);
    out.push_str("public val definition: WindowManifest =\n");
    out.push_str(INDENT2);
    out.push_str("WindowManifest(\n");
    out.push_str(INDENT2);
    out.push_str(INDENT);
    out.push_str("version = ");
    out.push_str(&manifest.version.to_string());
    out.push_str(",\n");
    out.push_str(INDENT2);
    out.push_str(INDENT);
    out.push_str("namespace = ");
    out.push_str(&kt_string(&manifest.namespace));
    out.push_str(",\n");
    out.push_str(INDENT2);
    out.push_str(INDENT);
    out.push_str("font = ");
    out.push_str(&kt_string(&manifest.font));
    out.push_str(",\n");
    out.push_str(INDENT2);
    out.push_str(INDENT);
    out.push_str("spacers = WindowSpacers.values,\n");
    out.push_str(INDENT2);
    out.push_str(INDENT);
    out.push_str("textAdvances = WindowFonts.advances,\n");
    out.push_str(INDENT2);
    out.push_str(INDENT);
    out.push_str("textGlyphWidths = WindowFonts.glyphWidths,\n");
    out.push_str(INDENT2);
    out.push_str(INDENT);
    out.push_str("fontMetrics = WindowFonts.metrics,\n");
    out.push_str(INDENT2);
    out.push_str(INDENT);
    out.push_str("sprites = WindowSprites.all,\n");
    out.push_str(INDENT2);
    out.push_str(INDENT);
    out.push_str("windows = WindowDefinitions.all,\n");
    out.push_str(INDENT2);
    out.push_str(INDENT);
    out.push_str("huds = WindowHudDefinitions.all,\n");
    out.push_str(INDENT2);
    out.push_str(")\n\n");
    out.push_str(INDENT);
    out.push_str("public fun windows(): Windows = Windows.load(definition)\n");
    out.push_str("}\n");
    out
}

fn generate_pack(manifest: &Manifest, package_name: &str) -> OutputFile {
    OutputFile { path: "WindowPack.kt".into(), contents: render_pack(manifest, package_name).into_bytes() }
}

fn generate_sprites(manifest: &Manifest, package_name: &str) -> OutputFile {
    OutputFile { path: "WindowSprites.kt".into(), contents: render_sprites(manifest, package_name).into_bytes() }
}

fn render_sprites(manifest: &Manifest, package_name: &str) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');
    out.push_str("package ");
    out.push_str(package_name);
    out.push_str("\n\n");
    out.push_str("import dev.oglass.window.manifest.SpriteEntry\n\n");
    out.push_str("/** Generated runtime sprite catalog for this Window pack. */\n");
    out.push_str("public object WindowSprites {\n");
    out.push_str(INDENT);
    out.push_str("val all: Map<String, SpriteEntry> =\n");
    out.push_str(INDENT2);
    out.push_str(&views::sprite_map_expr(&manifest.sprites, 2));
    out.push('\n');
    out.push_str("}\n");
    out
}

fn generate_spacers(manifest: &Manifest, package_name: &str) -> OutputFile {
    OutputFile { path: "WindowSpacers.kt".into(), contents: render_spacers(manifest, package_name).into_bytes() }
}

fn render_spacers(manifest: &Manifest, package_name: &str) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');
    out.push_str("package ");
    out.push_str(package_name);
    out.push_str("\n\n");
    out.push_str("/** Generated spacer glyph advances for the Window pack font. */\n");
    out.push_str("public object WindowSpacers {\n");
    out.push_str(INDENT);
    out.push_str("val values: Map<Int, Int> =\n");
    render_int_int_map(&mut out, &manifest.spacers, 2);
    out.push_str("}\n");
    out
}

fn generate_fonts(manifest: &Manifest, package_name: &str) -> OutputFile {
    OutputFile { path: "WindowFonts.kt".into(), contents: render_fonts(manifest, package_name).into_bytes() }
}

fn render_fonts(manifest: &Manifest, package_name: &str) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');
    out.push_str("package ");
    out.push_str(package_name);
    out.push_str("\n\n");
    out.push_str("import dev.oglass.window.manifest.FontMetricsEntry\n\n");
    out.push_str("/** Generated font metrics used for runtime text measurement. */\n");
    out.push_str("public object WindowFonts {\n");
    out.push_str(INDENT);
    out.push_str("val advances: Map<String, Int> =\n");
    render_char_int_map(&mut out, &manifest.text_advances, 2);
    out.push_str(INDENT);
    out.push_str("val glyphWidths: Map<String, Int> =\n");
    render_char_int_map(&mut out, &manifest.text_glyph_widths, 2);
    out.push_str(INDENT);
    out.push_str("private val vanillaMetrics: FontMetricsEntry =\n");
    out.push_str(INDENT2);
    out.push_str(&font_metrics_expr(
        &FontMetricsEntry {
            advances: manifest.text_advances.clone(),
            glyph_widths: manifest.text_glyph_widths.clone(),
            bold_advance: crate::vanilla::BOLD_ADVANCE,
        },
        "advances",
        "glyphWidths",
        2,
    ));
    out.push('\n');
    out.push_str(INDENT);
    out.push_str("val metrics: Map<String, FontMetricsEntry> =\n");
    if manifest.font_metrics.is_empty() {
        out.push_str(INDENT2);
        out.push_str("emptyMap()\n");
    } else {
        out.push_str(INDENT2);
        out.push_str("mapOf(\n");
        let vanilla = FontMetricsEntry {
            advances: manifest.text_advances.clone(),
            glyph_widths: manifest.text_glyph_widths.clone(),
            bold_advance: crate::vanilla::BOLD_ADVANCE,
        };
        for (font, metrics) in &manifest.font_metrics {
            out.push_str(INDENT2);
            out.push_str(INDENT);
            out.push_str(&kt_string(font));
            out.push_str(" to ");
            if metrics == &vanilla {
                out.push_str("vanillaMetrics");
            } else {
                out.push_str(&font_metrics_expr(metrics, "advances", "glyphWidths", 4));
            }
            out.push_str(",\n");
        }
        out.push_str(INDENT2);
        out.push_str(")\n");
    }
    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use crate::ir::{Align, ButtonDefault};
    use crate::manifest::{
        AnvilInputEntry, ButtonEntry, CollectionEntry, HudEntry, HudSurfaceEntry, ItemEntry, RepeatGroupEntry,
        SlotAreaEntry, SlotEntry, SlotRefEntry, SurfaceEntry, VERSION, WindowEntry,
    };

    use super::*;

    #[test]
    fn generates_typed_view() {
        let manifest = Manifest {
            version: VERSION,
            namespace: "window".into(),
            font: "window:ui".into(),
            spacers: BTreeMap::new(),
            text_advances: BTreeMap::new(),
            text_glyph_widths: BTreeMap::new(),
            font_metrics: BTreeMap::new(),
            sprites: BTreeMap::new(),
            windows: BTreeMap::from([(
                "shop".into(),
                WindowEntry {
                    surface: SurfaceEntry {
                        kind: "container".into(),
                        container: "generic_9x3".into(),
                        size: [176, 168],
                        title_origin: [8, 6],
                    },
                    static_text: String::new(),
                    slots: BTreeMap::from([
                        (
                            "balance".into(),
                            SlotEntry {
                                x: 8,
                                y: 24,
                                width: 160,
                                align: Align::Center,
                                font: "window:y18".into(),
                                color: "#ffffff".into(),
                                shader_marker: None,
                                shader_color: None,
                                shadow: false,
                                bold: false,
                                italic: false,
                                underlined: false,
                                strikethrough: false,
                                obfuscated: false,
                                text: None,
                            },
                        ),
                        (
                            "label_0".into(),
                            SlotEntry {
                                x: 8,
                                y: 6,
                                width: 160,
                                align: Align::Center,
                                font: "window:y0".into(),
                                color: "#ffd700".into(),
                                shader_marker: None,
                                shader_color: None,
                                shadow: false,
                                bold: false,
                                italic: false,
                                underlined: false,
                                strikethrough: false,
                                obfuscated: false,
                                text: Some("Black Market".into()),
                            },
                        ),
                        (
                            "entry_price_0".into(),
                            SlotEntry {
                                x: 8,
                                y: 54,
                                width: 40,
                                align: Align::Center,
                                font: "window:y48".into(),
                                color: "#ffffff".into(),
                                shader_marker: None,
                                shader_color: None,
                                shadow: false,
                                bold: false,
                                italic: false,
                                underlined: false,
                                strikethrough: false,
                                obfuscated: false,
                                text: None,
                            },
                        ),
                        (
                            "entry_price_1".into(),
                            SlotEntry {
                                x: 62,
                                y: 54,
                                width: 40,
                                align: Align::Center,
                                font: "window:y48".into(),
                                color: "#ffffff".into(),
                                shader_marker: None,
                                shader_color: None,
                                shadow: false,
                                bold: false,
                                italic: false,
                                underlined: false,
                                strikethrough: false,
                                obfuscated: false,
                                text: None,
                            },
                        ),
                    ]),
                    sprite_slots: BTreeMap::new(),
                    buttons: BTreeMap::from([
                        (
                            "entry_0".into(),
                            ButtonEntry {
                                x: 8,
                                y: 54,
                                width: 52,
                                height: 34,
                                slots: vec![
                                    SlotRefEntry { area: SlotAreaEntry::Container, index: 18 },
                                    SlotRefEntry { area: SlotAreaEntry::Container, index: 19 },
                                ],
                                fill_slots: Some(vec![SlotRefEntry { area: SlotAreaEntry::Container, index: 19 }]),
                                default: None,
                                action: true,
                                tooltip: None,
                                states: BTreeMap::new(),
                                sprite_font: None,
                            },
                        ),
                        (
                            "entry_1".into(),
                            ButtonEntry {
                                x: 62,
                                y: 54,
                                width: 52,
                                height: 34,
                                slots: vec![
                                    SlotRefEntry { area: SlotAreaEntry::Container, index: 21 },
                                    SlotRefEntry { area: SlotAreaEntry::Container, index: 22 },
                                ],
                                fill_slots: Some(vec![SlotRefEntry { area: SlotAreaEntry::Container, index: 22 }]),
                                default: None,
                                action: true,
                                tooltip: None,
                                states: BTreeMap::new(),
                                sprite_font: None,
                            },
                        ),
                        (
                            "exit".into(),
                            ButtonEntry {
                                x: 98,
                                y: 54,
                                width: 18,
                                height: 18,
                                slots: vec![SlotRefEntry { area: SlotAreaEntry::Container, index: 5 }],
                                fill_slots: None,
                                default: Some(ButtonDefault::Close),
                                action: true,
                                tooltip: None,
                                states: BTreeMap::new(),
                                sprite_font: None,
                            },
                        ),
                    ]),
                    items: BTreeMap::from([
                        (
                            "egg_info".into(),
                            ItemEntry { slots: vec![SlotRefEntry { area: SlotAreaEntry::Container, index: 7 }] },
                        ),
                        (
                            "entry_icon_0".into(),
                            ItemEntry { slots: vec![SlotRefEntry { area: SlotAreaEntry::Container, index: 18 }] },
                        ),
                        (
                            "entry_icon_1".into(),
                            ItemEntry { slots: vec![SlotRefEntry { area: SlotAreaEntry::Container, index: 21 }] },
                        ),
                    ]),
                    collections: BTreeMap::from([(
                        "entries".into(),
                        CollectionEntry {
                            slots: vec![SlotRefEntry { area: SlotAreaEntry::Container, index: 0 }],
                            action: true,
                        },
                    )]),
                    inputs: BTreeMap::new(),
                    slot_rects: BTreeMap::new(),
                    groups: BTreeMap::from([(
                        "entry".into(),
                        RepeatGroupEntry {
                            count: 2,
                            slots: BTreeMap::from([(
                                "price".into(),
                                vec!["entry_price_0".into(), "entry_price_1".into()],
                            )]),
                            sprite_slots: BTreeMap::new(),
                            items: BTreeMap::from([(
                                "icon".into(),
                                vec!["entry_icon_0".into(), "entry_icon_1".into()],
                            )]),
                            buttons: vec!["entry_0".into(), "entry_1".into()],
                        },
                    )]),
                },
            )]),
            huds: BTreeMap::new(),
        };

        let files = generate_kotlin(&manifest, "dev.oglass.window.example.generated").unwrap();
        assert_eq!(files.len(), 7);
        assert!(files.iter().any(|file| file.path == "WindowPack.kt"));
        assert!(files.iter().any(|file| file.path == "WindowFonts.kt"));
        assert!(files.iter().any(|file| file.path == "WindowSprites.kt"));
        assert!(files.iter().any(|file| file.path == "WindowSpacers.kt"));
        assert!(files.iter().any(|file| file.path == "WindowDefinitions.kt"));
        assert!(files.iter().any(|file| file.path == "WindowHudDefinitions.kt"));
        let view = files.iter().find(|file| file.path == "ShopView.kt").expect("ShopView.kt should be generated");
        let content = std::str::from_utf8(&view.contents).unwrap();
        assert!(content.contains("protected abstract fun balance(): Component"));
        assert!(content.contains("protected open fun onExit(click: Click): Unit = close()"));
        assert!(content.contains("protected abstract fun eggInfoItem(): ItemStack?"));
        assert!(content.contains("protected abstract fun entriesItem(index: Int): ItemStack?"));
        assert!(content.contains("protected abstract fun onEntries(click: IndexedClick)"));
        assert!(content.contains("protected abstract fun entryPrice(index: Int): Component"));
        assert!(content.contains("protected abstract fun onEntry(click: IndexedClick)"));
        assert!(content.contains("slot(\"balance\") { balance() }"));
        assert!(content.contains("slot(\"entry_price_0\") { entryPrice(0) }"));
        assert!(content.contains("button(\"entry_0\") { click ->"));
        assert!(content.contains("IndexedClick(click.player, click.slot, 0, click.shift, click.right)"));
        assert!(content.contains("item(\"egg_info\") { eggInfoItem() }"));
        // A repeater cell item is exposed as one grouped indexed member, not as
        // per-cell members, and the flattened per-cell names are bound for it.
        assert!(content.contains("protected abstract fun entryIconItem(index: Int): ItemStack?"));
        assert!(content.contains("item(\"entry_icon_0\") { entryIconItem(0) }"));
        assert!(content.contains("item(\"entry_icon_1\") { entryIconItem(1) }"));
        assert!(!content.contains("entryIcon0"));
        assert!(content.contains("collection(\"entries\", ::entriesItem, ::onEntries)"));
        assert!(!content.contains("entryPrice0"));
        assert!(!content.contains("label_0(): Component"));
    }

    #[test]
    fn generates_typed_anvil_input_binding() {
        let manifest = Manifest {
            version: VERSION,
            namespace: "window".into(),
            font: "window:ui".into(),
            spacers: BTreeMap::new(),
            text_advances: BTreeMap::new(),
            text_glyph_widths: BTreeMap::new(),
            font_metrics: BTreeMap::new(),
            sprites: BTreeMap::new(),
            windows: BTreeMap::from([(
                "search".into(),
                WindowEntry {
                    surface: SurfaceEntry {
                        kind: "container".into(),
                        container: "anvil".into(),
                        size: [176, 166],
                        title_origin: [60, 6],
                    },
                    static_text: String::new(),
                    slots: BTreeMap::new(),
                    sprite_slots: BTreeMap::new(),
                    buttons: BTreeMap::new(),
                    items: BTreeMap::new(),
                    collections: BTreeMap::new(),
                    inputs: BTreeMap::from([(
                        "query".into(),
                        AnvilInputEntry {
                            slot: SlotRefEntry { area: SlotAreaEntry::Container, index: 0 },
                            initial: "Search...".into(),
                            item_model: Some("demo:gui/search".into()),
                        },
                    )]),
                    slot_rects: BTreeMap::new(),
                    groups: BTreeMap::new(),
                },
            )]),
            huds: BTreeMap::new(),
        };

        let files = generate_kotlin(&manifest, "dev.oglass.window.generated").unwrap();
        let view = files.iter().find(|file| file.path == "SearchView.kt").expect("SearchView.kt should be generated");
        let content = std::str::from_utf8(&view.contents).unwrap();
        assert!(content.contains("protected abstract fun onQueryChanged(value: String)"));
        assert!(content.contains("anvilInput(\"query\", ::onQueryChanged)"));
    }

    #[test]
    fn hud_lifecycle_members_are_reserved() {
        let manifest = Manifest {
            version: VERSION,
            namespace: "window".into(),
            font: "window:ui".into(),
            spacers: BTreeMap::new(),
            text_advances: BTreeMap::new(),
            text_glyph_widths: BTreeMap::new(),
            font_metrics: BTreeMap::new(),
            sprites: BTreeMap::new(),
            windows: BTreeMap::new(),
            huds: BTreeMap::from([(
                "status".into(),
                HudEntry {
                    surface: HudSurfaceEntry {
                        kind: "hud".into(),
                        channel: "actionbar".into(),
                        width: 120,
                        height: 16,
                    },
                    static_text: String::new(),
                    slots: BTreeMap::from([(
                        "on_show".into(),
                        SlotEntry {
                            x: 0,
                            y: 0,
                            width: 80,
                            align: Align::Left,
                            font: "window:y0".into(),
                            color: "#ffffff".into(),
                            shader_marker: None,
                            shader_color: None,
                            shadow: false,
                            bold: false,
                            italic: false,
                            underlined: false,
                            strikethrough: false,
                            obfuscated: false,
                            text: None,
                        },
                    )]),
                    shader: None,
                },
            )]),
        };

        let err = generate_kotlin(&manifest, "dev.oglass.window.generated").unwrap_err();
        assert!(err.to_string().contains("reserved WindowView member `onShow`"), "{err}");
    }
}
