//! Minimal helpers for emitting indented Kotlin source.

use std::fmt::{Display, Write};

const HEADER: &str = "// Generated by window-codegen — do not edit.";
const INDENT: &str = "    ";

/// Line-oriented Kotlin source builder with a current indentation level.
pub(super) struct KotlinWriter {
    out: String,
    level: usize,
}

impl KotlinWriter {
    /// Starts a generated file with the header, package clause, and imports.
    pub(super) fn file<I: Display>(package_name: &str, imports: impl IntoIterator<Item = I>) -> Self {
        let mut out = format!("{HEADER}\npackage {package_name}\n\n");
        let mut has_imports = false;
        for import in imports {
            let _ = writeln!(out, "import {import}");
            has_imports = true;
        }
        if has_imports {
            out.push('\n');
        }
        Self { out, level: 0 }
    }

    /// Writes one line at the current level; embedded newlines are not re-indented.
    pub(super) fn line(&mut self, text: impl Display) {
        let _ = writeln!(self.out, "{}{text}", indent(self.level));
    }

    pub(super) fn blank(&mut self) {
        self.out.push('\n');
    }

    pub(super) fn doc(&mut self, text: impl Display) {
        self.line(format_args!("/** {text} */"));
    }

    /// Writes `text` and indents the following lines.
    pub(super) fn open(&mut self, text: impl Display) {
        self.line(text);
        self.level += 1;
    }

    /// Dedents and writes `text`.
    pub(super) fn close(&mut self, text: impl Display) {
        self.level -= 1;
        self.line(text);
    }

    /// Writes `declaration =` followed by `value` on the next, further-indented line.
    pub(super) fn property(&mut self, declaration: impl Display, value: impl Display) {
        self.line(format_args!("{declaration} ="));
        let _ = writeln!(self.out, "{}{value}", indent(self.level + 1));
    }

    pub(super) fn finish(self) -> String {
        self.out
    }
}

/// Builds a constructor call with one named argument per line, closed at `level`.
pub(super) struct Call {
    out: String,
    level: usize,
}

impl Call {
    pub(super) fn new(callee: &str, level: usize) -> Self {
        Self { out: format!("{callee}(\n"), level }
    }

    pub(super) fn arg(mut self, name: &str, value: impl Display) -> Self {
        let _ = writeln!(self.out, "{}{name} = {value},", indent(self.level + 1));
        self
    }

    pub(super) fn finish(mut self) -> String {
        self.out.push_str(&indent(self.level));
        self.out.push(')');
        self.out
    }
}

/// Renders `callee(` with one trailing-comma item per line, or `empty` when there are no items.
pub(super) fn multiline_call<T: Display>(
    callee: &str,
    empty: &str,
    items: impl IntoIterator<Item = T>,
    level: usize,
) -> String {
    let mut items = items.into_iter().peekable();
    if items.peek().is_none() {
        return empty.into();
    }
    let mut out = format!("{callee}(\n");
    for item in items {
        let _ = writeln!(out, "{}{item},", indent(level + 1));
    }
    out.push_str(&indent(level));
    out.push(')');
    out
}

pub(super) fn map_of<K: Display, V: Display>(entries: impl IntoIterator<Item = (K, V)>, level: usize) -> String {
    multiline_call("mapOf", "emptyMap()", entries.into_iter().map(|(key, value)| format!("{key} to {value}")), level)
}

pub(super) fn list_of<T: Display>(items: impl IntoIterator<Item = T>, level: usize) -> String {
    multiline_call("listOf", "emptyList()", items, level)
}

pub(super) fn indent(level: usize) -> String {
    INDENT.repeat(level)
}
