import { label, panel, slot, sprite } from "#plugins/window";

export default {
    huds: [
        {
            name: "status_top_left",
            channel: "actionbar",
            width: 118,
            height: 76,
            shader: { source_bottom: 59, origin: { x: 0.0, y: 0.0 }, anchor: { x: 0.0, y: 0.0 }, x: 8, y: 8 },
            children: [
                panel({ frame: "hud_panel", x: 0, y: 0, width: 118, height: 76 }),
                label("Economy", { x: 8, y: 8, width: 102, color: "#ffd700" }),
                panel({ frame: "hud_chip", x: 54, y: 24, width: 56, height: 14 }),
                panel({ frame: "hud_chip", x: 54, y: 40, width: 56, height: 14 }),
                panel({ frame: "hud_chip", x: 54, y: 56, width: 56, height: 14 }),
                label("Coins", { x: 8, y: 28, width: 44, color: "#a0a0a0" }),
                slot("coins", { x: 58, y: 28, width: 48, align: "right", color: "#ffffff" }),
                label("Rate", { x: 8, y: 44, width: 44, color: "#a0a0a0" }),
                slot("rate", { x: 58, y: 44, width: 48, align: "right", color: "#80ff80" }),
                label("Power", { x: 8, y: 60, width: 44, color: "#a0a0a0" }),
                slot("power", { x: 58, y: 60, width: 48, align: "right", color: "#80c0ff" }),
            ],
        },
        {
            name: "status_top_center",
            channel: "actionbar",
            width: 238,
            height: 24,
            shader: { source_bottom: 59, origin: { x: 0.5, y: 0.0 }, anchor: { x: 0.5, y: 0.0 }, x: 0, y: 8 },
            children: [
                panel({ frame: "hud_panel", x: 0, y: 0, width: 238, height: 24 }),
                sprite("pack_badge", { x: 150, y: 5 }),
                panel({ frame: "hud_chip", x: 184, y: 5, width: 48, height: 14 }),
                label("Window HUD", { x: 8, y: 8, width: 158, color: "#ffd700" }),
                slot("runtime", { x: 190, y: 8, width: 36, align: "center", color: "#ffffff" }),
            ],
        },
        {
            name: "status_top_right",
            channel: "actionbar",
            width: 118,
            height: 76,
            shader: { source_bottom: 59, origin: { x: 1.0, y: 0.0 }, anchor: { x: 1.0, y: 0.0 }, x: -8, y: 8 },
            children: [
                panel({ frame: "hud_panel", x: 0, y: 0, width: 118, height: 76 }),
                label("Run", { x: 8, y: 8, width: 102, color: "#ffd700" }),
                panel({ frame: "hud_chip", x: 54, y: 24, width: 56, height: 14 }),
                panel({ frame: "hud_chip", x: 54, y: 40, width: 56, height: 14 }),
                panel({ frame: "hud_chip", x: 54, y: 56, width: 56, height: 14 }),
                label("Wave", { x: 8, y: 28, width: 44, color: "#a0a0a0" }),
                slot("wave", { x: 58, y: 28, width: 48, align: "right", color: "#ffffff" }),
                label("Biome", { x: 8, y: 44, width: 44, color: "#a0a0a0" }),
                slot("biome", { x: 58, y: 44, width: 48, align: "right", color: "#80ff80" }),
                label("Ping", { x: 8, y: 60, width: 44, color: "#a0a0a0" }),
                slot("latency", { x: 58, y: 60, width: 48, align: "right", color: "#80c0ff" }),
            ],
        },
        {
            name: "status_left_side",
            channel: "actionbar",
            width: 136,
            height: 58,
            shader: { source_bottom: 59, origin: { x: 0.0, y: 0.5 }, anchor: { x: 0.0, y: 0.5 }, x: 8, y: 0 },
            children: [
                panel({ frame: "hud_panel", x: 0, y: 0, width: 136, height: 58 }),
                label("Position", { x: 8, y: 8, width: 120, color: "#ffd700" }),
                panel({ frame: "hud_chip", x: 8, y: 24, width: 120, height: 14 }),
                panel({ frame: "hud_chip", x: 8, y: 40, width: 120, height: 14 }),
                slot("coords", { x: 12, y: 28, width: 112, align: "center", color: "#ffffff" }),
                slot("altitude", { x: 12, y: 44, width: 112, align: "center", color: "#a0a0a0" }),
            ],
        },
        {
            name: "status_right_side",
            channel: "actionbar",
            width: 136,
            height: 58,
            shader: { source_bottom: 59, origin: { x: 1.0, y: 0.5 }, anchor: { x: 1.0, y: 0.5 }, x: -8, y: 0 },
            children: [
                panel({ frame: "hud_panel", x: 0, y: 0, width: 136, height: 58 }),
                label("Objective", { x: 8, y: 8, width: 120, color: "#ffd700" }),
                panel({ frame: "hud_chip", x: 8, y: 24, width: 120, height: 14 }),
                panel({ frame: "hud_chip", x: 8, y: 40, width: 120, height: 14 }),
                slot("objective", { x: 12, y: 28, width: 112, align: "center", color: "#ffffff" }),
                slot("stock", { x: 12, y: 44, width: 112, align: "center", color: "#a0a0a0" }),
            ],
        },
        {
            name: "status_bottom_center",
            channel: "actionbar",
            width: 184,
            height: 50,
            shader: { source_bottom: 59, origin: { x: 0.5, y: 1.0 }, anchor: { x: 0.5, y: 1.0 }, x: 0, y: -62 },
            children: [
                panel({ frame: "hud_focus", x: 0, y: 0, width: 184, height: 50 }),
                label("Status", { x: 12, y: 8, width: 160, align: "center", color: "#ffd700" }),
                panel({ frame: "hud_chip", x: 10, y: 26, width: 78, height: 14 }),
                panel({ frame: "hud_chip", x: 96, y: 26, width: 78, height: 14 }),
                slot("left_note", { x: 14, y: 30, width: 70, align: "center", color: "#ffffff" }),
                slot("right_note", { x: 100, y: 30, width: 70, align: "center", color: "#ffffff" }),
            ],
        },
    ],
};
