//! Pack-resident compiler expectations for render diagnostics.
//!
//! The compiled manifest remains the server runtime contract. This compact
//! descriptor is the client-facing companion: inspectors load it through
//! Minecraft's active resource manager and compare the real font/shader render
//! with the compiler's semantic expectations. It is emitted by default and is
//! regenerated byte-for-byte by compile-output validation.

mod glyphs;
mod resources;
mod schema;
mod surfaces;
#[cfg(test)]
mod tests;

use std::collections::BTreeMap;

use glyphs::{bitmap_resources_by_glyph, main_bitmap_glyphs, referenced_bitmap_resources};
pub use schema::{
    DebugAlphaMask, DebugCursorContract, DebugDescriptor, DebugFingerprint, DebugImage, DebugLayer, DebugResource,
    DebugSprite, DebugSurface, DebugTextStyle,
};
use surfaces::{hud_surface, window_surface};

use crate::manifest::Manifest;
use crate::pipeline::OutputFile;
use crate::{Error, Result};

/// Current debug descriptor schema version.
pub const VERSION: u32 = 1;

/// Filename, relative to a namespace's `assets/<namespace>/` directory.
pub const RESOURCE_PATH: &str = "window/debug.json";

impl DebugDescriptor {
    /// Build the descriptor expected for `manifest` and generated `files`.
    /// An existing debug descriptor in `files` is ignored.
    pub fn build(manifest: &Manifest, files: &[OutputFile]) -> Result<Self> {
        let descriptor_path = output_path(&manifest.namespace);
        let mut generated: Vec<&OutputFile> = files.iter().filter(|file| file.path != descriptor_path).collect();
        generated.sort_by(|left, right| left.path.cmp(&right.path));
        let file_map: BTreeMap<&str, &[u8]> =
            generated.iter().map(|file| (file.path.as_str(), file.contents.as_slice())).collect();
        let bitmap_glyphs = main_bitmap_glyphs(manifest, &file_map)?;
        let referenced = referenced_bitmap_resources(&generated)?;
        let glyph_resources = bitmap_resources_by_glyph(&generated)?;
        let resources = resources::describe(&generated, referenced)?;

        Ok(Self {
            schema_version: VERSION,
            compiler_version: env!("CARGO_PKG_VERSION").to_string(),
            manifest_version: manifest.version,
            namespace: manifest.namespace.clone(),
            pack_fingerprint: resources::pack_fingerprint(manifest, &generated)?,
            main_font: manifest.font.clone(),
            resources,
            sprites: sprite_catalog(manifest, &glyph_resources),
            windows: manifest
                .windows
                .iter()
                .map(|(name, window)| (name.clone(), window_surface(manifest, window, &bitmap_glyphs)))
                .collect(),
            huds: manifest
                .huds
                .iter()
                .map(|(name, hud)| (name.clone(), hud_surface(manifest, hud, &bitmap_glyphs)))
                .collect(),
        })
    }

    /// Serialize deterministically as compact JSON with a trailing newline.
    pub fn to_json_bytes(&self) -> Result<Vec<u8>> {
        let mut bytes = serde_json::to_vec(self).map_err(|error| Error::Manifest(error.to_string()))?;
        bytes.push(b'\n');
        Ok(bytes)
    }

    /// Parse and version-check an active-pack descriptor.
    pub fn from_json(bytes: &[u8]) -> Result<Self> {
        let descriptor: Self = serde_json::from_slice(bytes).map_err(|error| Error::Manifest(error.to_string()))?;
        if descriptor.schema_version != VERSION {
            return Err(Error::Manifest(format!(
                "unsupported debug descriptor version {} (expected {VERSION})",
                descriptor.schema_version
            )));
        }
        Ok(descriptor)
    }
}

/// Pack-output path for a namespace's descriptor.
pub fn output_path(namespace: &str) -> String {
    format!("assets/{namespace}/{RESOURCE_PATH}")
}

fn sprite_catalog(manifest: &Manifest, glyph_resources: &BTreeMap<char, String>) -> BTreeMap<String, DebugSprite> {
    manifest
        .sprites
        .iter()
        .map(|(name, sprite)| {
            (
                name.clone(),
                DebugSprite {
                    glyph: sprite.glyph.clone(),
                    ink_bounds: [sprite.x_offset, 0, sprite.glyph_width, sprite.height],
                    advance: sprite.advance,
                    resource: sprite.glyph.chars().next().and_then(|glyph| glyph_resources.get(&glyph).cloned()),
                },
            )
        })
        .collect()
}
