//! Pack-resident compiler expectations for render diagnostics.
//!
//! The compiled manifest remains the server runtime contract. This compact
//! descriptor is the client-facing companion: inspectors load it through
//! Minecraft's active resource manager and compare the real font/shader render
//! with the compiler's semantic expectations. It is emitted by default and is
//! regenerated byte-for-byte by compile-output validation.

use std::collections::{BTreeMap, BTreeSet};

use serde::{Deserialize, Serialize};
use serde_json::Value;
use sha2::{Digest, Sha256};

use crate::compose::Texture;
use crate::ir::Align;
use crate::manifest::{HudEntry, Manifest, SlotEntry, SpriteSlotEntry, WindowEntry};
use crate::pipeline::OutputFile;
use crate::{Error, Result};

/// Current debug descriptor schema version.
pub const VERSION: u32 = 1;

/// Filename, relative to a namespace's `assets/<namespace>/` directory.
pub const RESOURCE_PATH: &str = "window/debug.json";

/// The complete pack-resident debug descriptor.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugDescriptor {
    /// Descriptor schema version (== [`VERSION`]).
    pub schema_version: u32,
    /// Window compiler version that produced the descriptor.
    pub compiler_version: String,
    /// Compiled definition schema version.
    pub manifest_version: u32,
    /// Resource namespace containing this descriptor.
    pub namespace: String,
    /// Fingerprint of the canonical manifest and all generated pack artifacts
    /// except this descriptor.
    pub pack_fingerprint: DebugFingerprint,
    /// Main Window font used for static layers and cursor spacers.
    pub main_font: String,
    /// Generated and referenced resources needed by Window rendering.
    pub resources: BTreeMap<String, DebugResource>,
    /// Runtime sprite glyph catalog.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub sprites: BTreeMap<String, DebugSprite>,
    /// Window expectations by compiled definition id.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub windows: BTreeMap<String, DebugSurface>,
    /// HUD expectations by compiled definition id.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub huds: BTreeMap<String, DebugSurface>,
}

/// A named content digest.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugFingerprint {
    /// Digest algorithm. Version 1 always uses `sha256`.
    pub algorithm: String,
    /// Lowercase hexadecimal digest.
    pub value: String,
}

/// Cursor invariant for one render surface.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugCursorContract {
    /// Human/machine-readable convention id.
    pub convention: String,
    /// Required net advance for each layer when layers are independent. `None`
    /// means layers share a cursor and individual deltas depend on content and order.
    pub independent_layer_net_advance: Option<i32>,
    /// Required cursor advance of the fully composed surface.
    pub composed_advance: i32,
}

/// One pack resource involved in rendering.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugResource {
    /// Minecraft resource identifier where one exists.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resource_id: Option<String>,
    /// Pack-root-relative path for generated resources.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// Whether this compiler run emitted the resource.
    pub generated: bool,
    /// Generated byte length.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub byte_length: Option<u64>,
    /// SHA-256 of generated bytes.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fingerprint: Option<DebugFingerprint>,
    /// Decoded PNG geometry and ownership mask.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image: Option<DebugImage>,
}

/// PNG facts used for exact generated-layer checks and isolation.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugImage {
    /// Source image width in pixels.
    pub width: u32,
    /// Source image height in pixels.
    pub height: u32,
    /// Tight non-transparent bounds `[x, y, width, height]`, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub opaque_bounds: Option<[u32; 4]>,
    /// Compact row-major ownership mask for non-transparent pixels.
    pub alpha_mask: DebugAlphaMask,
}

/// A bounded-size bitmap ownership mask.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugAlphaMask {
    /// Encoding id. Version 1 uses `bitset_hex_msb0`: each pixel is one bit,
    /// first pixel in the high bit, with zero padding at the end.
    pub encoding: String,
    /// Lowercase hexadecimal encoded bitset.
    pub data: String,
}

/// Runtime sprite metrics shared by every vertically shifted sprite font.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugSprite {
    /// Allocated single-character glyph.
    pub glyph: String,
    /// Rendered sprite bounds `[x, y, width, height]` local to its slot.
    pub ink_bounds: [u32; 4],
    /// Minecraft cursor advance for the glyph.
    pub advance: u32,
    /// Bitmap resource rendered by the glyph.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
}

/// One Window or HUD surface.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugSurface {
    /// Surface kind (`container` or `hud`).
    pub kind: String,
    /// Container id or HUD channel.
    pub target: String,
    /// Surface bounds `[x, y, width, height]` in GUI space.
    pub bounds: [i32; 4],
    /// Cursor origin in GUI space.
    pub cursor_origin: [i32; 2],
    /// Cursor composition convention for this surface.
    pub cursor_contract: DebugCursorContract,
    /// Semantic layers in deterministic composition order.
    pub layers: Vec<DebugLayer>,
}

/// One semantic render layer.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugLayer {
    /// Stable semantic id (`static`, `text:<slot>`, `sprite:<slot>`).
    pub id: String,
    /// Layer kind (`static_chrome`, `text_slot`, or `sprite_slot`).
    pub kind: String,
    /// Expected/reserved GUI-space bounds `[x, y, width, height]`.
    pub bounds: [i32; 4],
    /// Font expected to render this layer.
    pub font: String,
    /// Bitmap glyph for a static layer.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub glyph: Option<String>,
    /// Static text content; absent for dynamic slots.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Font-provider ascent when fixed by compilation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ascent: Option<i32>,
    /// Raw content/glyph cursor advance before the compensating spacer.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_advance: Option<u32>,
    /// Cursor delta after this complete layer when statically meaningful.
    /// Shared-cursor HUD text layers use `null` because the delta depends on
    /// dynamic content and the preceding layers.
    pub net_advance: Option<i32>,
    /// Generated or referenced resource id for bitmap layers.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    /// Text/sprite alignment inside reserved bounds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub align: Option<Align>,
    /// Text style for text slots.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub style: Option<DebugTextStyle>,
}

/// Text style expected by a semantic text layer.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugTextStyle {
    /// Lowercase `#rrggbb` color.
    pub color: String,
    /// Vanilla shadow flag.
    pub shadow: bool,
    /// Bold decoration.
    pub bold: bool,
    /// Italic decoration.
    pub italic: bool,
    /// Underline decoration.
    pub underlined: bool,
    /// Strikethrough decoration.
    pub strikethrough: bool,
    /// Obfuscated decoration.
    pub obfuscated: bool,
}

#[derive(Clone, Debug)]
struct BitmapGlyph {
    file: String,
    ascent: i32,
    height: u32,
    advance: u32,
    width: u32,
}

impl DebugDescriptor {
    /// Build the descriptor expected for `manifest` and generated `files`.
    /// An existing debug descriptor in `files` is ignored.
    pub fn build(manifest: &Manifest, files: &[OutputFile]) -> Result<Self> {
        let descriptor_path = output_path(&manifest.namespace);
        let mut generated: Vec<&OutputFile> = files.iter().filter(|file| file.path != descriptor_path).collect();
        generated.sort_by(|left, right| left.path.cmp(&right.path));
        let file_map: BTreeMap<&str, &[u8]> =
            generated.iter().map(|file| (file.path.as_str(), file.contents.as_slice())).collect();
        let bitmap_glyphs = main_bitmap_glyphs(manifest, &file_map)?;
        let referenced = referenced_bitmap_resources(&generated)?;
        let glyph_resources = bitmap_resources_by_glyph(&generated)?;

        let mut resources = BTreeMap::new();
        for file in &generated {
            let resource_id = resource_id_from_path(&file.path);
            let image = if file.path.ends_with(".png") {
                Some(debug_image(
                    &Texture::decode_png(&file.contents)
                        .map_err(|error| Error::Texture { path: file.path.clone(), message: error.to_string() })?,
                ))
            } else {
                None
            };
            resources.insert(
                file.path.clone(),
                DebugResource {
                    resource_id,
                    path: Some(file.path.clone()),
                    generated: true,
                    byte_length: Some(file.contents.len() as u64),
                    fingerprint: Some(fingerprint(&file.contents)),
                    image,
                },
            );
        }
        let generated_ids: BTreeSet<String> =
            resources.values().filter_map(|resource| resource.resource_id.clone()).collect();
        for id in referenced {
            if !generated_ids.contains(&id) {
                resources.insert(
                    format!("resource:{id}"),
                    DebugResource {
                        resource_id: Some(id),
                        path: None,
                        generated: false,
                        byte_length: None,
                        fingerprint: None,
                        image: None,
                    },
                );
            }
        }

        let windows = manifest
            .windows
            .iter()
            .map(|(name, window)| (name.clone(), window_surface(manifest, window, &bitmap_glyphs)))
            .collect();
        let huds = manifest
            .huds
            .iter()
            .map(|(name, hud)| (name.clone(), hud_surface(manifest, hud, &bitmap_glyphs)))
            .collect();
        let sprites = manifest
            .sprites
            .iter()
            .map(|(name, sprite)| {
                (
                    name.clone(),
                    DebugSprite {
                        glyph: sprite.glyph.clone(),
                        ink_bounds: [sprite.x_offset, 0, sprite.glyph_width, sprite.height],
                        advance: sprite.advance,
                        resource: sprite.glyph.chars().next().and_then(|glyph| glyph_resources.get(&glyph).cloned()),
                    },
                )
            })
            .collect();

        Ok(Self {
            schema_version: VERSION,
            compiler_version: env!("CARGO_PKG_VERSION").to_string(),
            manifest_version: manifest.version,
            namespace: manifest.namespace.clone(),
            pack_fingerprint: pack_fingerprint(manifest, &generated)?,
            main_font: manifest.font.clone(),
            resources,
            sprites,
            windows,
            huds,
        })
    }

    /// Serialize deterministically as compact JSON with a trailing newline.
    pub fn to_json_bytes(&self) -> Result<Vec<u8>> {
        let mut bytes = serde_json::to_vec(self).map_err(|error| Error::Manifest(error.to_string()))?;
        bytes.push(b'\n');
        Ok(bytes)
    }

    /// Parse and version-check an active-pack descriptor.
    pub fn from_json(bytes: &[u8]) -> Result<Self> {
        let descriptor: Self = serde_json::from_slice(bytes).map_err(|error| Error::Manifest(error.to_string()))?;
        if descriptor.schema_version != VERSION {
            return Err(Error::Manifest(format!(
                "unsupported debug descriptor version {} (expected {VERSION})",
                descriptor.schema_version
            )));
        }
        Ok(descriptor)
    }
}

/// Pack-output path for a namespace's descriptor.
pub fn output_path(namespace: &str) -> String {
    format!("assets/{namespace}/{RESOURCE_PATH}")
}

fn fingerprint(bytes: &[u8]) -> DebugFingerprint {
    DebugFingerprint { algorithm: "sha256".into(), value: hex_digest(Sha256::digest(bytes)) }
}

fn pack_fingerprint(manifest: &Manifest, files: &[&OutputFile]) -> Result<DebugFingerprint> {
    let manifest = manifest.to_json_bytes()?;
    let mut digest = Sha256::new();
    digest.update(b"window-pack-debug-v1\0");
    update_framed(&mut digest, b"manifest");
    update_framed(&mut digest, &manifest);
    for file in files {
        update_framed(&mut digest, file.path.as_bytes());
        update_framed(&mut digest, &file.contents);
    }
    Ok(DebugFingerprint { algorithm: "sha256".into(), value: hex_digest(digest.finalize()) })
}

fn update_framed(digest: &mut Sha256, bytes: &[u8]) {
    digest.update((bytes.len() as u64).to_be_bytes());
    digest.update(bytes);
}

fn hex_digest(bytes: impl AsRef<[u8]>) -> String {
    use std::fmt::Write;
    let bytes = bytes.as_ref();
    let mut hex = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(&mut hex, "{byte:02x}").expect("writing to String cannot fail");
    }
    hex
}

fn debug_image(texture: &Texture) -> DebugImage {
    let mut min_x = u32::MAX;
    let mut min_y = u32::MAX;
    let mut max_x = 0;
    let mut max_y = 0;
    let mut found = false;
    let pixel_count = texture.width.saturating_mul(texture.height);
    let mut mask = vec![0u8; pixel_count.div_ceil(8) as usize];
    for index in 0..pixel_count {
        let alpha = texture.rgba[index as usize * 4 + 3];
        if alpha != 0 {
            let x = index % texture.width.max(1);
            let y = index / texture.width.max(1);
            min_x = min_x.min(x);
            min_y = min_y.min(y);
            max_x = max_x.max(x);
            max_y = max_y.max(y);
            found = true;
            mask[index as usize / 8] |= 1 << (7 - index % 8);
        }
    }
    DebugImage {
        width: texture.width,
        height: texture.height,
        opaque_bounds: if found { Some([min_x, min_y, max_x - min_x + 1, max_y - min_y + 1]) } else { None },
        alpha_mask: DebugAlphaMask { encoding: "bitset_hex_msb0".into(), data: hex_digest(mask) },
    }
}

fn main_bitmap_glyphs(manifest: &Manifest, files: &BTreeMap<&str, &[u8]>) -> Result<BTreeMap<char, BitmapGlyph>> {
    let path = font_output_path(&manifest.font);
    let bytes =
        files.get(path.as_str()).ok_or_else(|| Error::Manifest(format!("debug descriptor requires `{path}`")))?;
    let document: Value = serde_json::from_slice(bytes).map_err(|error| Error::Manifest(error.to_string()))?;
    let mut out = BTreeMap::new();
    for provider in document["providers"].as_array().into_iter().flatten() {
        if provider["type"].as_str() != Some("bitmap") {
            continue;
        }
        let file =
            provider["file"].as_str().ok_or_else(|| Error::Manifest("bitmap provider is missing file".into()))?;
        let height = provider["height"]
            .as_u64()
            .and_then(|value| u32::try_from(value).ok())
            .ok_or_else(|| Error::Manifest("bitmap provider has invalid height".into()))?;
        let ascent = provider["ascent"]
            .as_i64()
            .and_then(|value| i32::try_from(value).ok())
            .ok_or_else(|| Error::Manifest("bitmap provider has invalid ascent".into()))?;
        let texture_path = texture_output_path(file);
        let texture_bytes = files
            .get(texture_path.as_str())
            .ok_or_else(|| Error::Manifest(format!("bitmap provider resource `{file}` was not emitted")))?;
        let texture = Texture::decode_png(texture_bytes)
            .map_err(|error| Error::Texture { path: texture_path, message: error.to_string() })?;
        let rows =
            provider["chars"].as_array().ok_or_else(|| Error::Manifest("bitmap provider has invalid chars".into()))?;
        let row_count = u32::try_from(rows.len()).unwrap_or(u32::MAX).max(1);
        let cell_height = texture.height / row_count;
        for (row_index, row) in rows.iter().enumerate() {
            let row = row.as_str().ok_or_else(|| Error::Manifest("bitmap provider row is not a string".into()))?;
            let columns = u32::try_from(row.chars().count()).unwrap_or(u32::MAX).max(1);
            let cell_width = texture.width / columns;
            for (column_index, character) in row.chars().enumerate() {
                if character == '\0' {
                    continue;
                }
                let right = opaque_right(
                    &texture,
                    column_index as u32 * cell_width,
                    row_index as u32 * cell_height,
                    cell_width,
                    cell_height,
                );
                let visible = right.map_or(0, |right| right + 1);
                let scaled = scale_boundary(visible, cell_height.max(1), height);
                out.insert(
                    character,
                    BitmapGlyph {
                        file: file.to_string(),
                        ascent,
                        height,
                        advance: if visible == 0 { 0 } else { scaled + 1 },
                        width: scale_boundary(cell_width, cell_height.max(1), height),
                    },
                );
            }
        }
    }
    Ok(out)
}

fn opaque_right(texture: &Texture, x: u32, y: u32, width: u32, height: u32) -> Option<u32> {
    let mut right = None;
    for local_y in 0..height {
        for local_x in 0..width {
            let index = (((y + local_y) * texture.width + x + local_x) * 4 + 3) as usize;
            if texture.rgba.get(index).copied().unwrap_or(0) != 0 {
                right = Some(right.map_or(local_x, |current: u32| current.max(local_x)));
            }
        }
    }
    right
}

fn scale_boundary(value: u32, source_height: u32, rendered_height: u32) -> u32 {
    let value = u128::from(value);
    let source_height = u128::from(source_height.max(1));
    let rendered_height = u128::from(rendered_height);
    ((value * rendered_height * 2 + source_height) / (source_height * 2)).min(u128::from(u32::MAX)) as u32
}

fn window_surface(manifest: &Manifest, window: &WindowEntry, glyphs: &BTreeMap<char, BitmapGlyph>) -> DebugSurface {
    let origin = window.surface.title_origin;
    let mut layers: Vec<DebugLayer> =
        static_layer(manifest, &window.static_text, origin, glyphs, Some(0)).into_iter().collect();
    layers.extend(text_layers(manifest, &window.slots, origin[1], Some(0)));
    layers.extend(sprite_layers(&window.sprite_slots, origin[1], Some(0)));
    DebugSurface {
        kind: window.surface.kind.clone(),
        target: window.surface.container.clone(),
        bounds: [0, 0, window.surface.size[0] as i32, window.surface.size[1] as i32],
        cursor_origin: origin,
        cursor_contract: DebugCursorContract {
            convention: "independent_net_zero_segments".into(),
            independent_layer_net_advance: Some(0),
            composed_advance: 0,
        },
        layers,
    }
}

fn hud_surface(manifest: &Manifest, hud: &HudEntry, glyphs: &BTreeMap<char, BitmapGlyph>) -> DebugSurface {
    let origin = [0, 0];
    let width = hud.surface.width as i32;
    let independent_layer_net_advance = hud.shader.as_ref().map(|_| 0);
    let mut layers: Vec<DebugLayer> =
        static_layer(manifest, &hud.static_text, origin, glyphs, Some(width)).into_iter().collect();
    layers.extend(text_layers(manifest, &hud.slots, 0, independent_layer_net_advance));
    DebugSurface {
        kind: hud.surface.kind.clone(),
        target: hud.surface.channel.clone(),
        bounds: [0, 0, hud.surface.width as i32, hud.surface.height as i32],
        cursor_origin: origin,
        cursor_contract: DebugCursorContract {
            convention: if hud.shader.is_some() {
                "fixed_width_with_independent_overlays".into()
            } else {
                "fixed_width_shared_cursor".into()
            },
            independent_layer_net_advance,
            composed_advance: width,
        },
        layers,
    }
}

fn static_layer(
    manifest: &Manifest,
    text: &str,
    origin: [i32; 2],
    glyphs: &BTreeMap<char, BitmapGlyph>,
    net_advance: Option<i32>,
) -> Option<DebugLayer> {
    let mut cursor = 0i32;
    for character in text.chars() {
        if let Some(glyph) = glyphs.get(&character) {
            return Some(DebugLayer {
                id: "static".into(),
                kind: "static_chrome".into(),
                bounds: [origin[0] + cursor, origin[1] + 7 - glyph.ascent, glyph.width as i32, glyph.height as i32],
                font: manifest.font.clone(),
                glyph: Some(character.to_string()),
                content: None,
                ascent: Some(glyph.ascent),
                content_advance: Some(glyph.advance),
                net_advance,
                resource: Some(glyph.file.clone()),
                align: None,
                style: None,
            });
        }
        cursor = cursor.saturating_add(manifest.spacers.get(&(character as u32)).copied().unwrap_or(0));
    }
    None
}

fn text_layers(
    manifest: &Manifest,
    slots: &BTreeMap<String, SlotEntry>,
    title_y: i32,
    net_advance: Option<i32>,
) -> Vec<DebugLayer> {
    slots
        .iter()
        .map(|(name, slot)| DebugLayer {
            id: format!("text:{name}"),
            kind: "text_slot".into(),
            bounds: [slot.x, slot.y, slot.width as i32, 8],
            font: slot.font.clone(),
            glyph: None,
            content: slot.text.clone(),
            ascent: Some(7 - (slot.y - title_y)),
            content_advance: slot.text.as_deref().and_then(|text| text_advance(manifest, &slot.font, text, slot.bold)),
            net_advance,
            resource: None,
            align: Some(slot.align),
            style: Some(DebugTextStyle {
                color: slot.color.clone(),
                shadow: slot.shadow,
                bold: slot.bold,
                italic: slot.italic,
                underlined: slot.underlined,
                strikethrough: slot.strikethrough,
                obfuscated: slot.obfuscated,
            }),
        })
        .collect()
}

fn text_advance(manifest: &Manifest, font: &str, text: &str, bold: bool) -> Option<u32> {
    let metrics = manifest.font_metrics.get(font)?;
    text.chars().try_fold(0u32, |total, character| {
        let advance = metrics.advances.get(&character)?;
        Some(total.saturating_add(*advance).saturating_add(if bold { metrics.bold_advance } else { 0 }))
    })
}

fn sprite_layers(slots: &BTreeMap<String, SpriteSlotEntry>, title_y: i32, net_advance: Option<i32>) -> Vec<DebugLayer> {
    slots
        .iter()
        .map(|(name, slot)| DebugLayer {
            id: format!("sprite:{name}"),
            kind: "sprite_slot".into(),
            bounds: [slot.x, slot.y, slot.width as i32, slot.height as i32],
            font: slot.font.clone(),
            glyph: None,
            content: None,
            ascent: Some(7 - (slot.y - title_y)),
            content_advance: None,
            net_advance,
            resource: None,
            align: Some(slot.align),
            style: None,
        })
        .collect()
}

fn referenced_bitmap_resources(files: &[&OutputFile]) -> Result<BTreeSet<String>> {
    let mut referenced = BTreeSet::new();
    for file in files.iter().filter(|file| file.path.contains("/font/") && file.path.ends_with(".json")) {
        let document: Value = serde_json::from_slice(&file.contents)
            .map_err(|error| Error::Manifest(format!("{}: {error}", file.path)))?;
        for provider in document["providers"].as_array().into_iter().flatten() {
            if provider["type"].as_str() == Some("bitmap")
                && let Some(resource) = provider["file"].as_str()
            {
                referenced.insert(resource.to_string());
            }
        }
    }
    Ok(referenced)
}

fn bitmap_resources_by_glyph(files: &[&OutputFile]) -> Result<BTreeMap<char, String>> {
    let mut resources = BTreeMap::new();
    for file in files.iter().filter(|file| file.path.contains("/font/") && file.path.ends_with(".json")) {
        let document: Value = serde_json::from_slice(&file.contents)
            .map_err(|error| Error::Manifest(format!("{}: {error}", file.path)))?;
        for provider in document["providers"].as_array().into_iter().flatten() {
            let Some(resource) = provider["file"].as_str() else {
                continue;
            };
            for row in provider["chars"].as_array().into_iter().flatten() {
                for glyph in row.as_str().into_iter().flat_map(str::chars) {
                    if glyph != '\0' {
                        resources.entry(glyph).or_insert_with(|| resource.to_string());
                    }
                }
            }
        }
    }
    Ok(resources)
}

fn font_output_path(font: &str) -> String {
    let (namespace, path) = font.split_once(':').unwrap_or(("minecraft", font));
    format!("assets/{namespace}/font/{path}.json")
}

fn texture_output_path(resource: &str) -> String {
    let (namespace, path) = resource.split_once(':').unwrap_or(("minecraft", resource));
    format!("assets/{namespace}/textures/{path}")
}

fn resource_id_from_path(path: &str) -> Option<String> {
    let rest = path.strip_prefix("assets/")?;
    let (namespace, path) = rest.split_once('/')?;
    let resource_path = if let Some(path) = path.strip_prefix("textures/") {
        path.to_string()
    } else {
        let path = path.strip_prefix("font/")?;
        path.strip_suffix(".json")?.to_string()
    };
    Some(format!("{namespace}:{resource_path}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pipeline::{CompileInput, compile_project_json};

    const PROJECT: &str = r##"{
      "theme":{"frames":{"panel":{"kind":"panel","fill":"#123456","border_width":0,"radius":0,"inset_depth":0}}},
      "windows":[{"name":"sample","container":"generic_9x3","children":[
        {"type":"panel","frame":"panel","x":8,"y":0,"width":16,"height":16},
        {"type":"label","text":"Hi","x":8,"y":20,"width":30},
        {"type":"slot","name":"value","x":8,"y":30,"width":30}
      ]}]
    }"##;

    #[test]
    fn emitted_descriptor_parses_and_describes_semantic_layers() {
        let output = compile_project_json(PROJECT.as_bytes(), &CompileInput::new(BTreeMap::new())).unwrap();
        let file = output.files.iter().find(|file| file.path == output_path("window")).unwrap();
        let descriptor = DebugDescriptor::from_json(&file.contents).unwrap();
        assert_eq!(descriptor.pack_fingerprint.algorithm, "sha256");
        assert_eq!(descriptor.pack_fingerprint.value.len(), 64);
        assert_eq!(descriptor.resources["assets/window/font/ui.json"].resource_id.as_deref(), Some("window:ui"));
        assert_eq!(descriptor.windows["sample"].cursor_origin, [8, 6]);
        assert_eq!(
            descriptor.windows["sample"].cursor_contract,
            DebugCursorContract {
                convention: "independent_net_zero_segments".into(),
                independent_layer_net_advance: Some(0),
                composed_advance: 0,
            }
        );
        assert_eq!(
            descriptor.windows["sample"].layers.iter().map(|layer| layer.id.as_str()).collect::<Vec<_>>(),
            vec!["static", "text:label_0", "text:value"]
        );
        assert!(descriptor.windows["sample"].layers.iter().all(|layer| layer.net_advance == Some(0)));
        assert!(
            descriptor
                .resources
                .values()
                .any(|resource| { resource.image.as_ref().is_some_and(|image| !image.alpha_mask.data.is_empty()) })
        );
    }

    #[test]
    fn descriptor_is_byte_identical_when_rebuilt() {
        let output = compile_project_json(PROJECT.as_bytes(), &CompileInput::new(BTreeMap::new())).unwrap();
        let emitted = output.files.iter().find(|file| file.path == output_path("window")).unwrap();
        let rebuilt = DebugDescriptor::build(&output.manifest, &output.files).unwrap().to_json_bytes().unwrap();
        assert_eq!(emitted.contents, rebuilt);

        let mut reversed = output.files.clone();
        reversed.reverse();
        let rebuilt_from_reversed =
            DebugDescriptor::build(&output.manifest, &reversed).unwrap().to_json_bytes().unwrap();
        assert_eq!(rebuilt, rebuilt_from_reversed);
    }

    #[test]
    fn hud_descriptor_distinguishes_shared_and_independent_fixed_width_overlays() {
        let project = r##"{
          "theme":{"frames":{"panel":{"kind":"panel","fill":"#123456","border_width":0,"radius":0,"inset_depth":0}}},
          "huds":[
            {"name":"shared","channel":"actionbar","width":40,"height":12,"children":[
              {"type":"panel","frame":"panel","x":0,"y":0,"width":8,"height":8},
              {"type":"slot","name":"value","x":2,"y":2,"width":20}
            ]},
            {"name":"shader","channel":"actionbar","width":48,"height":12,
             "shader":{"source_bottom":59,"origin":{"x":0.5,"y":0.0},"anchor":{"x":0.5,"y":0.0}},
             "children":[{"type":"slot","name":"value","x":3,"y":2,"width":20}]}
          ]
        }"##;
        let output = compile_project_json(project.as_bytes(), &CompileInput::new(BTreeMap::new())).unwrap();
        let file = output.files.iter().find(|file| file.path == output_path("window")).unwrap();
        let descriptor = DebugDescriptor::from_json(&file.contents).unwrap();

        let shared = &descriptor.huds["shared"];
        assert_eq!(shared.cursor_contract.convention, "fixed_width_shared_cursor");
        assert_eq!(shared.cursor_contract.independent_layer_net_advance, None);
        assert_eq!(shared.cursor_contract.composed_advance, 40);
        assert_eq!(shared.layers[0].kind, "static_chrome");
        assert_eq!(shared.layers[0].net_advance, Some(40));
        assert_eq!(shared.layers[1].net_advance, None);

        let shader = &descriptor.huds["shader"];
        assert_eq!(shader.cursor_contract.convention, "fixed_width_with_independent_overlays");
        assert_eq!(shader.cursor_contract.independent_layer_net_advance, Some(0));
        assert_eq!(shader.cursor_contract.composed_advance, 48);
        assert_eq!(shader.layers[0].net_advance, Some(0));
    }
}
