package dev.oglass.window.codegen

import dev.oglass.window.codegen.manifest.Manifest
import dev.oglass.window.codegen.manifest.ManifestHud
import dev.oglass.window.codegen.manifest.ManifestWindow

/** A generated source file: its on-disk name and full text. */
internal data class GeneratedFile(
    val fileName: String,
    val content: String,
)

/** Raised when a manifest cannot be turned into valid, unambiguous Kotlin. */
internal class GenerationException(
    message: String,
) : Exception(message)

/**
 * Renders typed [dev.oglass.window.WindowView] subclasses from a parsed manifest.
 *
 * Output is deterministic: windows and members are emitted in sorted order, with `\n` line endings,
 * a fixed header, 4-space indentation, and exactly one trailing newline.
 */
internal object Generator {
    /** First line of every generated file; used to identify stale files for deletion/`--check`. */
    const val HEADER: String = "// Generated by window-codegen — do not edit."

    /** Generate one [GeneratedFile] per window/HUD, sorted by file name. */
    fun generate(
        manifest: Manifest,
        packageName: String,
    ): List<GeneratedFile> =
        buildList {
            for ((name, window) in manifest.windows.entries.sortedBy { it.key }) {
                add(generateWindow(name, window, packageName))
            }
            for ((name, hud) in manifest.huds.entries.sortedBy { it.key }) {
                add(generateHud(name, hud, packageName))
            }
        }.sortedBy { it.fileName }

    private fun generateWindow(
        windowName: String,
        window: ManifestWindow,
        packageName: String,
    ): GeneratedFile {
        val className = Naming.className(windowName)

        // Dynamic slots only (skip static labels carrying `text`), sorted by manifest name.
        val dynamicSlots =
            window.slots
                .filterValues { it.text == null }
                .keys
                .sorted()
        val spriteSlots =
            window.spriteSlots
                .filterValues { it.sprite == null }
                .keys
                .sorted()
        val buttonNames =
            window.buttons
                .filterValues { it.action }
                .keys
                .sorted()
        val itemNames = window.items.keys.sorted()
        val collectionNames = window.collections.keys.sorted()
        val inputNames = window.inputs.keys.sorted()

        // Build members, checking identifier validity and collisions as we go.
        val taken = mutableMapOf<String, String>() // member name -> "kind `source`"
        val members = mutableListOf<Member>()
        val groupedSlots = mutableSetOf<String>()
        val groupedSpriteSlots = mutableSetOf<String>()
        val groupedButtons = mutableSetOf<String>()

        for ((groupName, group) in window.groups.entries.sortedBy { it.key }) {
            for ((field, rawSources) in group.slots.entries.sortedBy { it.key }) {
                val sources = rawSources.filter { it.isNotEmpty() }
                if (sources.isEmpty()) continue
                val member = Naming.slotMember("${groupName}_$field")
                checkMember(member, "repeater `$groupName` slot `$field`", className, taken)
                groupedSlots += sources
                members += Member.GroupSlot(groupName, field, sources, member)
            }
            for ((field, rawSources) in group.spriteSlots.entries.sortedBy { it.key }) {
                val sources = rawSources.filter { it.isNotEmpty() }
                if (sources.isEmpty()) continue
                val member = "${Naming.slotMember("${groupName}_$field")}Sprite"
                checkMember(member, "repeater `$groupName` sprite slot `$field`", className, taken)
                groupedSpriteSlots += sources
                members += Member.GroupSprite(groupName, field, sources, member)
            }
            val buttonSources = group.buttons.filter { it.isNotEmpty() }
            if (buttonSources.isNotEmpty()) {
                val member = Naming.buttonMember(groupName)
                checkMember(member, "repeater `$groupName` button", className, taken)
                groupedButtons += buttonSources
                members += Member.GroupButton(groupName, buttonSources, member)
            }
        }

        for (slot in dynamicSlots) {
            if (slot in groupedSlots) continue
            val member = Naming.slotMember(slot)
            checkMember(member, "slot `$slot`", className, taken)
            members += Member.Slot(slot, member)
        }
        for (slot in spriteSlots) {
            if (slot in groupedSpriteSlots) continue
            val member = "${Naming.slotMember(slot)}Sprite"
            checkMember(member, "sprite slot `$slot`", className, taken)
            members += Member.Sprite(slot, member)
        }
        for (button in buttonNames) {
            if (button in groupedButtons) continue
            val member = Naming.buttonMember(button)
            val isClose = window.buttons.getValue(button).default == "close"
            checkMember(member, "button `$button`", className, taken)
            members += Member.Button(button, member, isClose)
        }
        for (item in itemNames) {
            val member = "${Naming.slotMember(item)}Item"
            checkMember(member, "item `$item`", className, taken)
            members += Member.Item(item, member)
        }
        for (collection in collectionNames) {
            val itemMember = "${Naming.slotMember(collection)}Item"
            checkMember(itemMember, "collection `$collection` item", className, taken)
            val handler =
                if (window.collections.getValue(collection).action) {
                    Naming.buttonMember(collection).also {
                        checkMember(it, "collection `$collection`", className, taken)
                    }
                } else {
                    null
                }
            members += Member.Collection(collection, itemMember, handler)
        }
        for (input in inputNames) {
            val member = "${Naming.buttonMember(input)}Changed"
            checkMember(member, "anvil input `$input`", className, taken)
            members += Member.AnvilInput(input, member)
        }

        val content = render(packageName, windowName, className, members)
        return GeneratedFile("$className.kt", content)
    }

    private fun generateHud(
        hudName: String,
        hud: ManifestHud,
        packageName: String,
    ): GeneratedFile {
        val className = Naming.hudClassName(hudName)
        val dynamicSlots =
            hud.slots
                .filterValues { it.text == null }
                .keys
                .sorted()
        val taken = mutableMapOf<String, String>()
        val members = mutableListOf<Member.Slot>()

        for (slot in dynamicSlots) {
            val member = Naming.slotMember(slot)
            checkMember(member, "slot `$slot`", className, taken)
            members += Member.Slot(slot, member)
        }

        val content = renderHud(packageName, hudName, className, members)
        return GeneratedFile("$className.kt", content)
    }

    private fun checkMember(
        member: String,
        source: String,
        className: String,
        taken: MutableMap<String, String>,
    ) {
        if (!Naming.isValidIdentifier(member)) {
            throw GenerationException(
                "$source in window maps to invalid Kotlin identifier `$member` (class $className)",
            )
        }
        if (member in Naming.reservedMembers) {
            throw GenerationException(
                "$source collides with reserved WindowView member `$member` (class $className)",
            )
        }
        val existing = taken[member]
        if (existing != null) {
            throw GenerationException(
                "$source and $existing both map to member `$member` (class $className)",
            )
        }
        taken[member] = source
    }

    private fun render(
        packageName: String,
        windowName: String,
        className: String,
        members: List<Member>,
    ): String {
        val hasButton = members.any { it is Member.Button }
        val hasSlot = members.any { it is Member.Slot || it is Member.GroupSlot }
        val hasItem = members.any { it is Member.Item || it is Member.Collection }
        val hasIndexedClick = members.any { it is Member.Collection && it.handler != null }
        val hasGroupedButton = members.any { it is Member.GroupButton }

        val sb = StringBuilder()
        sb.append(HEADER).append('\n')
        sb.append("package ").append(packageName).append("\n\n")
        // Emit only the imports the body uses, sorted. WindowScope/WindowView are used by bind().
        if (hasButton) sb.append("import dev.oglass.window.Click\n")
        if (hasIndexedClick || hasGroupedButton) {
            sb.append("import dev.oglass.window.IndexedClick\n")
        }
        sb.append("import dev.oglass.window.WindowScope\n")
        sb.append("import dev.oglass.window.WindowView\n")
        if (hasSlot) sb.append("import net.kyori.adventure.text.Component\n")
        if (hasItem) sb.append("import net.minestom.server.item.ItemStack\n")
        sb.append('\n')

        // A window with no dynamic slots and no buttons still generates as an open class.
        val classKeyword = if (members.isEmpty()) "open" else "abstract"
        sb
            .append("/** Typed view for the `")
            .append(windowName)
            .append("` window. Implement the abstract members. */\n")
        sb
            .append("public ")
            .append(classKeyword)
            .append(" class ")
            .append(className)
            .append(" : WindowView(\"")
            .append(windowName)
            .append("\") {\n")

        for (member in members) {
            when (member) {
                is Member.Slot -> {
                    sb
                        .append(INDENT)
                        .append("/** Render the `")
                        .append(member.source)
                        .append("` slot. */\n")
                    sb
                        .append(INDENT)
                        .append("protected abstract fun ")
                        .append(member.member)
                        .append("(): Component\n\n")
                }

                is Member.Button -> {
                    if (member.isClose) {
                        sb
                            .append(INDENT)
                            .append("/** Handle a click on the `")
                            .append(member.source)
                            .append("` button (default: close the window). */\n")
                        sb
                            .append(INDENT)
                            .append("protected open fun ")
                            .append(member.member)
                            .append("(click: Click): Unit = close()\n\n")
                    } else {
                        sb
                            .append(INDENT)
                            .append("/** Handle a click on the `")
                            .append(member.source)
                            .append("` button. */\n")
                        sb
                            .append(INDENT)
                            .append("protected abstract fun ")
                            .append(member.member)
                            .append("(click: Click)\n\n")
                    }
                }

                is Member.Sprite -> {
                    sb
                        .append(INDENT)
                        .append("/** Render the `")
                        .append(member.source)
                        .append("` runtime sprite id. */\n")
                    sb
                        .append(INDENT)
                        .append("protected abstract fun ")
                        .append(member.member)
                        .append("(): String?\n\n")
                }

                is Member.GroupSlot -> {
                    sb
                        .append(INDENT)
                        .append("/** Render one `")
                        .append(member.field)
                        .append("` slot in the `")
                        .append(member.group)
                        .append("` repeater. */\n")
                    sb
                        .append(INDENT)
                        .append("protected abstract fun ")
                        .append(member.member)
                        .append("(index: Int): Component\n\n")
                }

                is Member.GroupSprite -> {
                    sb
                        .append(INDENT)
                        .append("/** Render one `")
                        .append(member.field)
                        .append("` runtime sprite id in the `")
                        .append(member.group)
                        .append("` repeater. */\n")
                    sb
                        .append(INDENT)
                        .append("protected abstract fun ")
                        .append(member.member)
                        .append("(index: Int): String?\n\n")
                }

                is Member.GroupButton -> {
                    sb
                        .append(INDENT)
                        .append("/** Handle a click on the `")
                        .append(member.group)
                        .append("` repeater. */\n")
                    sb
                        .append(INDENT)
                        .append("protected abstract fun ")
                        .append(member.member)
                        .append("(click: IndexedClick)\n\n")
                }

                is Member.Item -> {
                    sb
                        .append(INDENT)
                        .append("/** Render the `")
                        .append(member.source)
                        .append("` inventory item. */\n")
                    sb
                        .append(INDENT)
                        .append("protected abstract fun ")
                        .append(member.member)
                        .append("(): ItemStack?\n\n")
                }

                is Member.Collection -> {
                    sb
                        .append(INDENT)
                        .append("/** Render one cell in the `")
                        .append(member.source)
                        .append("` collection. */\n")
                    sb
                        .append(INDENT)
                        .append("protected abstract fun ")
                        .append(member.itemMember)
                        .append("(index: Int): ItemStack?\n\n")
                    member.handler?.let { handler ->
                        sb
                            .append(INDENT)
                            .append("/** Handle a click on the `")
                            .append(member.source)
                            .append("` collection. */\n")
                        sb
                            .append(INDENT)
                            .append("protected abstract fun ")
                            .append(handler)
                            .append("(click: IndexedClick)\n\n")
                    }
                }

                is Member.AnvilInput -> {
                    sb
                        .append(INDENT)
                        .append("/** Handle a value change from the native `")
                        .append(member.source)
                        .append("` anvil input. */\n")
                    sb
                        .append(INDENT)
                        .append("protected abstract fun ")
                        .append(member.member)
                        .append("(value: String)\n\n")
                }
            }
        }

        sb.append(INDENT).append("final override fun WindowScope.bind() {\n")
        if (members.isEmpty()) {
            // Replace the opening with an empty body.
            sb.setLength(sb.length - "{\n".length)
            sb.append("{}\n")
        } else {
            for (member in members) {
                when (member) {
                    is Member.Slot -> {
                        sb
                            .append(INDENT2)
                            .append("slot(\"")
                            .append(member.source)
                            .append("\") { ")
                            .append(member.member)
                            .append("() }\n")
                    }

                    is Member.Button -> {
                        sb
                            .append(INDENT2)
                            .append("button(\"")
                            .append(member.source)
                            .append("\", ::")
                            .append(member.member)
                            .append(")\n")
                    }

                    is Member.Sprite -> {
                        sb
                            .append(INDENT2)
                            .append("sprite(\"")
                            .append(member.source)
                            .append("\") { ")
                            .append(member.member)
                            .append("() }\n")
                    }

                    is Member.GroupSlot -> {
                        member.sources.forEachIndexed { index, source ->
                            sb
                                .append(INDENT2)
                                .append("slot(\"")
                                .append(source)
                                .append("\") { ")
                                .append(member.member)
                                .append("(")
                                .append(index)
                                .append(") }\n")
                        }
                    }

                    is Member.GroupSprite -> {
                        member.sources.forEachIndexed { index, source ->
                            sb
                                .append(INDENT2)
                                .append("sprite(\"")
                                .append(source)
                                .append("\") { ")
                                .append(member.member)
                                .append("(")
                                .append(index)
                                .append(") }\n")
                        }
                    }

                    is Member.GroupButton -> {
                        member.sources.forEachIndexed { index, source ->
                            sb
                                .append(INDENT2)
                                .append("button(\"")
                                .append(source)
                                .append("\") { click ->\n")
                                .append(INDENT2)
                                .append(INDENT)
                                .append(member.member)
                                .append("(\n")
                                .append(INDENT2)
                                .append(INDENT2)
                                .append("IndexedClick(click.player, click.slot, ")
                                .append(index)
                                .append(", click.shift, click.right)\n")
                                .append(INDENT2)
                                .append(INDENT)
                                .append(")\n")
                                .append(INDENT2)
                                .append("}\n")
                        }
                    }

                    is Member.Item -> {
                        sb
                            .append(INDENT2)
                            .append("item(\"")
                            .append(member.source)
                            .append("\") { ")
                            .append(member.member)
                            .append("() }\n")
                    }

                    is Member.Collection -> {
                        if (member.handler != null) {
                            sb
                                .append(INDENT2)
                                .append("collection(\"")
                                .append(member.source)
                                .append("\", ::")
                                .append(member.itemMember)
                                .append(", ::")
                                .append(member.handler)
                                .append(")\n")
                        } else {
                            sb
                                .append(INDENT2)
                                .append("collectionItem(\"")
                                .append(member.source)
                                .append("\", ::")
                                .append(member.itemMember)
                                .append(")\n")
                        }
                    }

                    is Member.AnvilInput -> {
                        sb
                            .append(INDENT2)
                            .append("anvilInput(\"")
                            .append(member.source)
                            .append("\", ::")
                            .append(member.member)
                            .append(")\n")
                    }
                }
            }
            sb.append(INDENT).append("}\n")
        }

        sb.append("}\n")
        return sb.toString()
    }

    private fun renderHud(
        packageName: String,
        hudName: String,
        className: String,
        members: List<Member.Slot>,
    ): String {
        val hasSlot = members.isNotEmpty()

        val sb = StringBuilder()
        sb.append(HEADER).append('\n')
        sb.append("package ").append(packageName).append("\n\n")
        sb.append("import dev.oglass.window.HudScope\n")
        sb.append("import dev.oglass.window.HudView\n")
        if (hasSlot) sb.append("import net.kyori.adventure.text.Component\n")
        sb.append('\n')

        val classKeyword = if (members.isEmpty()) "open" else "abstract"
        sb
            .append("/** Typed view for the `")
            .append(hudName)
            .append("` HUD. Implement the abstract members. */\n")
        sb
            .append("public ")
            .append(classKeyword)
            .append(" class ")
            .append(className)
            .append(" : HudView(\"")
            .append(hudName)
            .append("\") {\n")

        for (member in members) {
            sb
                .append(INDENT)
                .append("/** Render the `")
                .append(member.source)
                .append("` slot. */\n")
            sb
                .append(INDENT)
                .append("protected abstract fun ")
                .append(member.member)
                .append("(): Component\n\n")
        }

        sb.append(INDENT).append("final override fun HudScope.bind() {\n")
        if (members.isEmpty()) {
            sb.setLength(sb.length - "{\n".length)
            sb.append("{}\n")
        } else {
            for (member in members) {
                sb
                    .append(INDENT2)
                    .append("slot(\"")
                    .append(member.source)
                    .append("\") { ")
                    .append(member.member)
                    .append("() }\n")
            }
            sb.append(INDENT).append("}\n")
        }

        sb.append("}\n")
        return sb.toString()
    }

    private const val INDENT = "    "
    private const val INDENT2 = "        "

    private sealed interface Member {
        data class Slot(
            val source: String,
            val member: String,
        ) : Member

        data class Button(
            val source: String,
            val member: String,
            val isClose: Boolean,
        ) : Member

        data class Sprite(
            val source: String,
            val member: String,
        ) : Member

        data class GroupSlot(
            val group: String,
            val field: String,
            val sources: List<String>,
            val member: String,
        ) : Member

        data class GroupSprite(
            val group: String,
            val field: String,
            val sources: List<String>,
            val member: String,
        ) : Member

        data class GroupButton(
            val group: String,
            val sources: List<String>,
            val member: String,
        ) : Member

        data class Item(
            val source: String,
            val member: String,
        ) : Member

        data class Collection(
            val source: String,
            val itemMember: String,
            val handler: String?,
        ) : Member

        data class AnvilInput(
            val source: String,
            val member: String,
        ) : Member
    }
}
