use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::ir::Align;

/// The complete pack-resident debug descriptor.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugDescriptor {
    /// Descriptor schema version (== [`super::VERSION`]).
    pub schema_version: u32,
    /// Window compiler version that produced the descriptor.
    pub compiler_version: String,
    /// Compiled definition schema version.
    pub manifest_version: u32,
    /// Resource namespace containing this descriptor.
    pub namespace: String,
    /// Fingerprint of the canonical manifest and all generated pack artifacts
    /// except this descriptor.
    pub pack_fingerprint: DebugFingerprint,
    /// Main Window font used for static layers and cursor spacers.
    pub main_font: String,
    /// Generated and referenced resources needed by Window rendering.
    pub resources: BTreeMap<String, DebugResource>,
    /// Runtime sprite glyph catalog.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub sprites: BTreeMap<String, DebugSprite>,
    /// Window expectations by compiled definition id.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub windows: BTreeMap<String, DebugSurface>,
    /// HUD expectations by compiled definition id.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub huds: BTreeMap<String, DebugSurface>,
}

/// A named content digest.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugFingerprint {
    /// Digest algorithm. Version 1 always uses `sha256`.
    pub algorithm: String,
    /// Lowercase hexadecimal digest.
    pub value: String,
}

/// Cursor invariant for one render surface.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugCursorContract {
    /// Human/machine-readable convention id.
    pub convention: String,
    /// Required net advance for each layer when layers are independent. `None`
    /// means layers share a cursor and individual deltas depend on content and order.
    pub independent_layer_net_advance: Option<i32>,
    /// Required cursor advance of the fully composed surface.
    pub composed_advance: i32,
}

/// One pack resource involved in rendering.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugResource {
    /// Minecraft resource identifier where one exists.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resource_id: Option<String>,
    /// Pack-root-relative path for generated resources.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// Whether this compiler run emitted the resource.
    pub generated: bool,
    /// Generated byte length.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub byte_length: Option<u64>,
    /// SHA-256 of generated bytes.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fingerprint: Option<DebugFingerprint>,
    /// Decoded PNG geometry and ownership mask.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image: Option<DebugImage>,
}

/// PNG facts used for exact generated-layer checks and isolation.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugImage {
    /// Source image width in pixels.
    pub width: u32,
    /// Source image height in pixels.
    pub height: u32,
    /// Tight non-transparent bounds `[x, y, width, height]`, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub opaque_bounds: Option<[u32; 4]>,
    /// Compact row-major ownership mask for non-transparent pixels.
    pub alpha_mask: DebugAlphaMask,
}

/// A bounded-size bitmap ownership mask.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugAlphaMask {
    /// Encoding id. Version 1 uses `bitset_hex_msb0`: each pixel is one bit,
    /// first pixel in the high bit, with zero padding at the end.
    pub encoding: String,
    /// Lowercase hexadecimal encoded bitset.
    pub data: String,
}

/// Runtime sprite metrics shared by every vertically shifted sprite font.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugSprite {
    /// Allocated single-character glyph.
    pub glyph: String,
    /// Rendered sprite bounds `[x, y, width, height]` local to its slot.
    pub ink_bounds: [u32; 4],
    /// Minecraft cursor advance for the glyph.
    pub advance: u32,
    /// Bitmap resource rendered by the glyph.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
}

/// One Window or HUD surface.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugSurface {
    /// Surface kind (`container` or `hud`).
    pub kind: String,
    /// Container id or HUD channel.
    pub target: String,
    /// Surface bounds `[x, y, width, height]` in GUI space.
    pub bounds: [i32; 4],
    /// Cursor origin in GUI space.
    pub cursor_origin: [i32; 2],
    /// Cursor composition convention for this surface.
    pub cursor_contract: DebugCursorContract,
    /// Semantic layers in deterministic composition order.
    pub layers: Vec<DebugLayer>,
}

/// One semantic render layer.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugLayer {
    /// Stable semantic id (`static`, `case:<switch>/<value>`, `text:<slot>`, `sprite:<slot>`).
    pub id: String,
    /// Layer kind (`static_chrome`, `case_chrome`, `text_slot`, or `sprite_slot`).
    pub kind: String,
    /// Expected/reserved GUI-space bounds `[x, y, width, height]`.
    pub bounds: [i32; 4],
    /// Font expected to render this layer.
    pub font: String,
    /// Bitmap glyph for a static layer.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub glyph: Option<String>,
    /// Static text content; absent for dynamic slots.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Font-provider ascent when fixed by compilation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ascent: Option<i32>,
    /// Raw content/glyph cursor advance before the compensating spacer.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_advance: Option<u32>,
    /// Cursor delta after this complete layer when statically meaningful.
    /// Shared-cursor HUD text layers use `null` because the delta depends on
    /// dynamic content and the preceding layers.
    pub net_advance: Option<i32>,
    /// Generated or referenced resource id for bitmap layers.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    /// Text/sprite alignment inside reserved bounds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub align: Option<Align>,
    /// Text style for text slots.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub style: Option<DebugTextStyle>,
    /// The authored element a derived layer comes from, such as ``tab `category_new` ``.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

/// Text style expected by a semantic text layer.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DebugTextStyle {
    /// Lowercase `#rrggbb` color.
    pub color: String,
    /// Vanilla shadow flag.
    pub shadow: bool,
    /// Bold decoration.
    pub bold: bool,
    /// Italic decoration.
    pub italic: bool,
    /// Underline decoration.
    pub underlined: bool,
    /// Strikethrough decoration.
    pub strikethrough: bool,
    /// Obfuscated decoration.
    pub obfuscated: bool,
}
